### ISSUE TITLE
Bugs MoreMesecons

### ISSUE THREAD

**Issue by mgl512** [Mynetest/Mynetest-server#100]
`moremesecons_signalchanger:signalchanger_off` incraftable. La recette ne donne rien.

**Comment by paly2** [comment]
https://github.com/minetest-mods/MoreMesecons/commit/aa54d34b5a727d51c10093308aa48b726d7ea099

**Comment by matt8fr** [comment]
Le serveur est dans la panade depuis hier et je pense que c'est du a MoreMescons.

**Comment by paly2** [comment]
Un reboot a semblé suffire...

Note: pour rebooter le serveur en tant que l'utilisateur minetest, en SSH, la commande est `killall -SIGUSR1 minetestserver`. Je dis ça parce que j'ai reçu un rapport du système m'indiquant que l'utilisateur `minetest` avait essayé d'utiliser `sudo` (sans appartenir au groupe `sudoers`) pour exécuter le script init.d du minetestserver afin de le redémarrer

**Comment by matt8fr** [comment]
j'ai tenter en jeu des /error moi je n'est pas accès au ssh 😄

**Comment by mgl512** [comment]
Pas moi non plus. Je ne sais même pas qui a un accès ssh à part JAPP.

**Comment by paly2** [comment]
C'était JAPP qui a rebooté le serveur 😃 Il a ensuite utilisé la bonne commande

**Comment by paly2** [comment]
Les bugs du wireless ont disparu après avoir largement modifié le code (trop modifié pour que je sache exactement ce qui coinçait).

**Comment by mega-gigaMynetest** [comment]
Note: pour rebooter le serveur en tant que l'utilisateur minetest, en SSH, la commande est killall -SIGUSR1 minetestserver

Merci paly2, grâce a cette issue j'ai pu aujourd'hui relancer le serveur sans avoir a attendre toi au JAPP, maintenant si je la reoublie, je sais ou la trouver !

**Comment by paly2** [comment]
La commande n'est à utiliser que si rien d'autre n'est possible - en effet, le serveur semble ne pas automatiquement kicker les joueurs lorsqu'il est arrêté de cette façon. Ceci, ça devrait pouvoir être arrangé dans l'engine, je regarderai ça.
