### ISSUE TITLE
Les batiments et travelnets de MT_Satellite sont pas les notres

### ISSUE THREAD

**Issue by mgl512** [Mynetest/Mynetest-server#101]
Tout est en allemand avec des pointeurs qui disent n'importe quoi.

**Comment by paly2** [comment]
Je sais :) C'est un fichier de test (pour tester le nouveau JavaScript permettant d'afficher ces pointeurs, non inclu dans la version publiée sur BitBucket de MTSatellite). Le mod qui permettra de le générer automatiquement n'est pas encore terminé.

Ce fichier est celui utilisé sur [la map de Sascha L. Teichmann](http://maps.mt.sha-bang.de/#3/0.00/0.00)

**Comment by paly2** [comment]
* Pour ajouter un bâtiment sur la map (à votre position actuelle): `/add_building <nom>`
* Pour supprimer un bâtiment: `/remove_building <ID>`
* Pour obtenir la position d'un bâtiment (et son ID): `/find_building <regexp>`. Cette commande est la seule des trois à ne pas nécessiter le privilège `mtsatellite`.
