### ISSUE TITLE
Problèmes potentiels maj MT_game

### ISSUE THREAD

**Issue by mgl512** [Mynetest/Mynetest-server#102]
Voilà ce que j'ai remarqué dans les dernières mises à jour de minetest_game:

1. Les coffres deviennent Minecraft-like: Ils ont un état "ouvert" avec animation.
Les blocs placés au dessus d'eux pourraient les empêcher de s'ouvrir, comme les distributeurs "vending machines". Ce n'est pas le cas pour le moment mais c'est comme ça sur Minecraft il me semble.

2. Ajout du minerais "étain" (tin) => conflits avec le mod moreores
Je ne sais pas si moreores est vraiment maintenu, il est plutôt inactif ou il attendait peut-être cette maj de minetest_game. Ils acceptent les PR en tout cas. 
default:stone_with_tin  = moreores:mineral_tin
default:tin_lump = moreores:tin_lump,
default:tin_ingot = moreores:tin_ingot,
default:tinblock  = moreores:tin_block

**Comment by matt8fr** [comment]
effectivement c'est comme ça sur Minecraft, espérons qu'ils ont uniquement ajouter l'animation.
sinon pour les vending machine il faudra casser la machine et la replacer/configuré a chaque foi.

**Comment by mgl512** [comment]
Il y a un moment, Thomas S a soumis une pull request pour moreores où le mod ne définit pas de tin s'il existe dans minetest_game et crée des alias. Du code de transition à garder "un certain temps" dans moreores. De mon côté, j'en ai soumis une où le support du tin disparait complètement sans aucune préoccupation pour les vieux mondes et c'est aux joueurs qui ont un jeu où il existe du tin de moreores qui doivent mettre les alias dans un mod pour éviter les "unknown blocks". Je préfère la mienne parce ça ne repose pas sur le fait que ce soit moreores qui garde les alias "un certain temps". Au bout d'un moment, on va oublier que c'est lui qui fait ça pour Mynetest par exemple, le mettre à jour alors qu'il a abandonné le support du tin et on ne le remarquera pas en test. Et des joueurs vont trouver des blocs inconnus en minant... Le mainteneur du mod n'a pas l'air très actif. 

Mais je poste surtout ce message parce que le serveur Mynetest a l'air d'avoir disparu de l'univers. Grossam, lui, a posté un message sur le forum.

**Comment by paly2** [comment]
Le serveur est revenu.

Pour les coffres, s'il n'y a qu'une animation, tout va bien ;-)
Pour le tin, j'ai effectivement vu la pull request de Thomas--S, raison pour laquelle je n'ai pas soumise la mienne. En attendant, on peut faire des `minetest.register_alias_force` dans le mod misc.

**Comment by paly2** [comment]
https://github.com/Mynetest/Mynetest-server/commit/47b4d9a1a8b46f43664528cae4fd270b57cb777f
