### ISSUE TITLE
Les hopper ne fonctionnent plus avec les nouveau coffre animé

### ISSUE THREAD

**Issue by YruamaLairba** [Mynetest/Mynetest-server#104]
Salut, Je viens de constater que les hopper ne fonctionnent plus avec les nouveau coffres qui ont une animation d'ouverture.

**Comment by YruamaLairba** [comment]
Même problème avec les vending machines, elles ne semblent plus voir les coffres.

**Comment by mgl512** [comment]
Je me doutais que ça pouvait arriver mais je n'ai pas eu le temps de tester en singleplayer avant la maj du serveur. On dirait que c'est réglé upstream pour le mod hoppers. Pour les vending machines, je n'ai pas regardé. Les nouveaux coffres risquent de poser des problèmes à plusieurs mods pendant un moment.

**Comment by mgl512** [comment]
Avec le commit référencé, les hoppers et vending machines remarchent. Le souci c'est que si on ouvre un coffre pendant qu'un hopper le remplit, on voit pas de changement dans le coffre. Il se remplit bien mais quand on l'ouvre pour regarder dedans, c'est une photographie du moment où on l'a ouvert qu'on voit. On le voit plus se remplir en direct.

**Comment by paly2** [comment]
Super, merci pour la mise à jour 😃 C'est sûr que c'est moins bien si le formspec ne se met pas à jour en direct
