### ISSUE TITLE
Player position is 0,0,0 on join

### ISSUE THREAD

**Issue by paly2** [Mynetest/Mynetest-server#15]
When a player joins, its position is 0,0,0 instead of his old position.

I tried to look at all Lua `minetest.on_joinplayer`s. I also looked at the C++ source code. I did not understand the cause of this problem...

**Comment by AcidNinjaFWHR** [comment]
Ok i'll have a look

**Comment by AcidNinjaFWHR** [comment]
Is there a static_spawnpoint set in minetest.conf ?

**Comment by AcidNinjaFWHR** [comment]
hummm
found it I think it's the mod first_hour which causes the issue i'll try to fix it locally and test and tell you

**Comment by AcidNinjaFWHR** [comment]
I can't reproduce on my local server alone, it works great.

**Comment by paly2** [comment]
Working again :-)

Thanks !

**Comment by paly2** [comment]
The bug is back

**Comment by mgl512** [comment]
Il a toujours été là : j'apparais régulièrement en (0,0,0). Je suppose que c'est la lenteur de la transmission des données qui fait ça. On apparait en (0,0,0) à la connexion et le client commence à chuter jusqu'à tomber sur la plaque de pression qui téléporte dans la bulle de verre du spawn. Ça se passe avant que le serveur ait le temps de transmettre les dernières coordonnées connues. 

On a connu quelque chose comme ça avec MFF1 en sortant du nether: on se retrouvait en l'air, a tomber sur un arbre de jungle de la plage du spawn au lieu de se retrouver au point de retour normal du portail public. Parce que le client traite les données plus vite que le serveur ne les envoie.

**Comment by AcidNinjaFWHR** [comment]
Corrigé en upstream: https://github.com/minetest/minetest/pull/4812

Faut attendre un peu que minetest_game et les autres mods soient adaptés à mon avis. (A tester).

**Comment by AcidNinjaFWHR** [comment]
Grace à la pull request https://github.com/minetest/minetest/pull/4812
le bug en upstream https://github.com/minetest/minetest/issues/4403 est résolu.

Je ferme ce ticket.
