### ISSUE TITLE
xban fail ?

### ISSUE THREAD

**Issue by mgl512** [Mynetest/Mynetest-server#18]
Un joueur banni a pu se reconnecter 1 minute plus tard. La deuxième commande de ban est la première rappelée par scroll up de l'historique des commandes.  Elle a marché la deuxième fois, j'ai surveillé les logs pendant quelques minutes. EDIT: Il n'a pas essayé de se reconnecter d'après les logs, donc je ne sais pas si le ban a marché.

```
2016-09-17 11:54:41: ACTION[Server]: Le_Docteur kicks Victor84
2016-09-17 11:54:41: ACTION[Server]: Victor84 leaves game. List of players: ... 
2016-09-17 11:55:07: ACTION[Server]: [xban] Le_Docteur bans Victor84 until dim. 18 sept. 2016 11:55:07 CEST for reason: Grief
2016-09-17 11:56:36: ACTION[Server]: Victor84 [88.8.153.189] joins game. 
2016-09-17 11:56:36: ACTION[Server]: Victor84 joins game. List of players: ... Victor84
2016-09-17 11:58:00: ACTION[Server]: [xban] Le_Docteur bans Victor84 until dim. 18 sept. 2016 11:58:00 CEST for reason: Grief
2016-09-17 11:58:00: ACTION[Server]: Victor84 leaves game. List of players: ...
```

Il faisait du grief sur le bateau pas encore protégé que koala construisait. Il ne parle pas français je crois

**Comment by paly2** [comment]
Les données de xban2 sont correctes. En simulant, au moyen de la commande //lua de WorldEdit, l'exécution du callback on_prejoinplayer lancé quand Victor84 établit la connexion avec le serveur, j'obtiens les bons résultats.

Ma seule hypotèse: le client de Victor84 se débrouille pour se connecter en ignorant le retour de ce callback (qui est bien appelé, pourtant, j'en suis pratiquement sûr). C'est la même hypotèse que pour expliquer le fait que names_per_ip soit totalement inefficace sur certains clients.

**Comment by mgl512** [comment]
Le client cheaté volontairement, je n'y crois pas trop. Quand il y en a un qui arrive a mettre un return true pour cheater fly, noclip, fast et zoom, il se prend pour un hacker. Je suppose que c'est plus compliqué de cheater les protocoles réseaux parce que les "hackers" n'arrivent pas à revenir quand ils se font ban.

**Comment by paly2** [comment]
Peut-être que le client n'est pas cheaté volontairement, et qu'il s'agit d'un fork... Ou d'une ancienne version (avec un ancien protocole).

**Comment by AcidNinjaFWHR** [comment]
Le fonctionnement de blocage de client banni semble situé ici:

https://github.com/minetest/minetest/blob/0b0075e6ad0b3110cabdfc92cedb0a24d2b5ec42/src/server.cpp#L1149

Si je n em'abuse on ne fait que vérifier si l'adresse IP du client est bannie "getPeerAddress(peer_id)",
le user Victor84 aurait-il pu changer d'adresse IP (1m30 depuis son ban quand il se reconnecte, cela peut être un reboot de box ADSL, chez de nombreux FAI, l'ip est dynamique :) ).

En plus, on ne voit qu'une IP dans ton extrait de log, ça met le doute.

**Comment by mgl512** [comment]
xban2 est censé bannir l'IP, le pseudo et tout ce qu'il peut rattacher à l'un ou à l'autre. Il est censé transmettre une copie à lui d'ipban.txt au serveur sans jamais réécrire l'ipban.txt existant. Il ratisse très large. 

J'ai été moi-même banni en cascade deux fois par xban2. A l'époque du Grand Usurpateur. Il s'emparait de comptes sans mot de passe et transférait les richesses de compte à compte. verrouillant son compte final par un mot de passe. Uraza et moi avons usurpé nous aussi des comptes de joueurs pour vérifier qui n'avait pas de mot de passe. Je me souviens du cas stayfino l'usurpé: il se connecte, prétend être le vrai qui n'arrive pas à mettre un mot de passe. Il rage, quitte et se connecte avec la même ip et le pseudo usurpé final sans tenir compte de la casse. Je le ban immédiatement avec xban2. xban2 met sa traque en route et retrouve que je me suis connecté moi aussi sous le pseudo de stayfino et il me ban en cascade. (C'était le vrai stayfino, qui avait l'habitude de se connecter sous des pseudos voisins d'autres joueurs)

**Comment by paly2** [comment]
> J'ai été moi-même banni en cascade deux fois par xban2. A l'époque du Grand Usurpateur. Il s'emparait de comptes sans mot de passe et transférait les richesses de compte à compte. verrouillant son compte final par un mot de passe. Uraza et moi avons usurpé nous aussi des comptes de joueurs pour vérifier qui n'avait pas de mot de passe.

Raison pour laquelle nous avons à la suite de ces événements implémenté une whitelist à xban2, de joueurs (et d'IPs) totalement ignorés par xban2 et conservés absents de sa base de données (sauf, bien sûr, de la table de joueurs whitelistés...). Ces joueurs (les modérateurs) peuvent donc usurper les comptes des joueurs sans problème de "ban en cascade". Tous les joueurs avec le priv ban peuvent modifier la whitelist (avec les commandes /xban_ignore et /xban_unignore).
