### ISSUE TITLE
Replace farming_plus by this new implementation

### ISSUE THREAD

**Issue by AcidNinjaFWHR** [Mynetest/Mynetest-server#23]
https://github.com/tenplus1/farming

it's better,
actively supported (farming_plus is inactive since July 2014)
and is compatible with farming_plus nodes.

**Comment by paly2** [comment]
Good idea :-)

**Comment by mgl512** [comment]
Il y a juste la lumière : les choses poussaient avec une lumière de 8 pour farming_plus. C'est 13 pour farming_redo. Plus rien ne poussera sous terre (ou presque si les torches éclairent au maximum, 14), ce qui est plutôt embêtant sur un serveur ou l'espace est limité.

**Comment by paly2** [comment]
https://github.com/tenplus1/farming/commit/fcf4600dda982d8f85236deb59d161f836e4d0cc sur le submodule et https://github.com/paly2/Mynetest-server/commit/79624aa835ca625d237548ab7a191315b3a3e90a sur le dépôt parent corrigent assez proprement (enfin, je suppose) ce problème de lumière (impossible à corriger depuis un mod externe) tout en gardant farming sous forme de submodule.

**Comment by mgl512** [comment]
Des blocs farming_plus:cocoa_sapling sont toujours là. Certains ont disparu mais ça doit être une intervention à  amain.

**Comment by AcidNinjaFWHR** [comment]
Ça a été corrigé en upstream.
https://github.com/tenplus1/farming/commit/8afc6ffb86927487d9902047ee545d8af9689152

Il faut mettre à jour notre fork et réappliquer le changement du MIN_LIGHT = 8

**Comment by AcidNinjaFWHR** [comment]
Submitted to upstream repo: https://github.com/tenplus1/farming/issues/19

**Comment by paly2** [comment]
Super, pour le changement de l'alias ! Et très bonne idée, l'issue pour le min_light.

**Comment by AcidNinjaFWHR** [comment]
Utilisant notre fork, la correction de lumière nous convient (le dépot Upstream n'a rien fait concernant notre demande, tantpis). Je clos ce ticket.

**Comment by mgl512** [comment]
Le sapling de cacao "unknown block" est toujours là.

**Comment by mgl512** [comment]
Enfin réglé !
Les blocs se sont transformés en cacao jaune et tombent en cacao en grain, surement parce qu'il n'y a pas de tronc de jungle comme voisin.
