### ISSUE TITLE
grief de chemin de fer épique

### ISSUE THREAD

**Issue by mgl512** [Mynetest/Mynetest-server#25]
Le rollback des actions du joueur n'a pas fonctionné jusqu'au bout. Plein de blocs censés être inclus dedans sont restés. j'en ai refait un deuxième avec la même durée qui n'a rien changé. C'est Daeam le joueur. 

Le grief commençait en (-640, -710). c'était un épiquement long chemin de bois sur l'eau avec un début de rail tout au sud. Le rollback a réussi jusqu'en (0, -1840) et echoué au delà. Le rail va jusqu'en (-70, -3430). Au sud-ouest de cette position il y a deux haies de centaines de saplings plus ou moins poussés: jungle sur un axe nord-sud et defaut d'est en ouest. Ces haies géantes devaient l'alimenter en planches. Elles ont été partiellement qupprimées par le rollback. Et il y avait un champ sur une colline (-180, -3545). Il avait commencé à doubler la largeur du chemin en bois de jungle pour faire courir des fils électriques le long des rails et alimenter les boosters. 

Il reste surtout un très long chemin de planches sur l'eau. 

Il y a même au moins un canal artificiel (115, -2300) le long duquel court le chemin de bois. Et des piquets posés pour faire une immense area. J'espère que c'était pas un projet pour le serveur. La première impression, quand on voit le chemin, est "Grief épique" mais ça pourrait être du build de malade impossible à maintenir

**Comment by paly2** [comment]
Je vois en effet l'impressionnant chemin sur la map. Je pense qu'il s'agissait bien d'un build. Personne n'aurait fait tant d'efforts (il a dû falloir beaucoup de temps pour construire tout ça) uniquement pour faire du grief.

Je propose déjà d'unban Daeam afin qu'il puisse nous expliquer - et probablement de ne pas le reban étant donné qu'il avait vraisemblablement de bonnes intentions.

Je ne sais pas pour quelle raison le rollback n'a pas fonctionner, je suppose qu'il faut que les mapblocks soient chargés. N'essaie pas de faire fonctionner la fin du rollback, si Daeam compte en faire  quelque chose (on pourra toujours le détruire au WE, il n'y a rien en planches de bois à part ce chemin dans cette zone).

Pour l'area, c'est en effet inconcevable. En revanche il est possible de faire plusieurs petites areas.

**Comment by mgl512** [comment]
Il est unban et j'ai prévenu (mail) Fox de ne pas détruire son chemin de bois. J'ai aussi envoyé un mail à ce joueur pour lui dire de contacter l'admin par la commande /mail éventuellement.

**Comment by mgl512** [comment]
J'ai croisé Daeam en jeu. Il parle anglais. Il ne construit pas un chemin de fer gigantesque sur l'eau mais des canaux. Le bois doit lui servir de repère et je ne sais pas pourquoi il avait commencé à mettre des rails et des boosters dans la zone la plus au sud. 

En gros je lui ai confirmé qu'il avait le feu vert pour continuer et qu'on l'aiderait à protéger ses trucs qu'il comptait segmenter avec des areas. Je ne sais pas trop ce qu'il faudra protéger si c'est des canaux. On verra. mais il a bien parlé de bateaux et pas de rails.

**Comment by mgl512** [comment]
C'est un chemin de fer qu'il construit. Il double l'épaisseur de la voie pour faire courir du mesefil le long des rails pour alimenter les boosters. Les boosters modifiés par Mg pour être autoalimentés sur MFF1 étaient mieux pour le paysage. Je n'ai rien protégé encore.

**Comment by paly2** [comment]
En effet il vaut mieux que les rails soient auto-alimentés.

https://github.com/Mynetest/Mynetest-server/commit/e7cbe9fd4be4362b3cadda112bf42f9e45e37ae4 supprime l'effet de mesecons sur ces rails et les rend accélérants dès qu'ils sont posés. Le mesecons reste cependant tout à fait fonctionnel sur les start-stop-rail, par exemple (ce qui permet un certain niveau d'automatisation d'un réseau de carts, par exemple des aiguillages, je suppose).

**Comment by mgl512** [comment]
Tout devrait être protégé (public) sur ce chemin de fer large de 2 blocs et très long.

**Comment by mgl512** [comment]
> Tout devrait être protégé (public) sur ce chemin de fer large de 2 blocs et très long

Non. Il semble que Daeam ait supprimé les areas lui appartenant encore parce que les rails n'étaientt pas posés. J'aurais pu les transférer à "public" mais hors de question que je perde mon temps à les refaire.

**Comment by paly2** [comment]
> Non. Il semble que Daeam ait supprimé les areas lui appartenant encore parce que les rails n'étaient pas posés.

-_- Pourquoi n'a-t-il pas posé les rails sans supprimer les areas ?
