### ISSUE TITLE
Mod Hoppers pour "remplacer" Pipeworks ?

### ISSUE THREAD

**Issue by mgl512** [Mynetest/Mynetest-server#29]
C'est une suggestion de joueurs pour avoir un peu de mécanisation. Je n'ai jamais utilisé ce mod. Il est sur le forum Minetest.

**Comment by AcidNinjaFWHR** [comment]
Intéressant.
A tester le fork de tenplus1: https://github.com/tenplus1/hopper

**Comment by paly2** [comment]
Pourquoi pas ! Comme il n'y a pas de transfert d'entités dans les hopper (contrairement aux tubes pipeworks), le lag devrait être largement inférieur. Pas de risque de sur-drop non plus, vu que les hoppers sont incapables de dropper. Je regrette juste que ce mod soit Minecraft-like.

J'ajoute le fork de TenPlus1 (mieux optimisé que le mod original).

**Comment by paly2** [comment]
https://github.com/Mynetest/Mynetest-server/commit/58c4a51ea7f108bfe565fb1d0abb347f9b16806f
