### ISSUE TITLE
Skin admin/modo ?

### ISSUE THREAD

**Issue by AcidNinjaFWHR** [Mynetest/Mynetest-server#30]
avec ce mod: https://github.com/PilzAdam/player_textures
on pourrait utiliser des skins qui ne soient pas présent dans le GUI de sélection des skins par les joueurs,

ça nous permettrait par exemple d'avoir un skin mod/admin voir tout autre.
exemple: skin joint

![player_upsilon](https://cloud.githubusercontent.com/assets/20411249/19275354/b84a7e74-8fd3-11e6-8a73-a919b87c6359.png)

**Comment by paly2** [comment]
Ce mod va entrer en conflit avec u_skins. Ça va être la guerre pour choisir de quel mod le joueur prendra le skin.
De plus player_textures n'est vraiment pas pratique à utiliser, il faut mettre les textures dans le dossier du monde. Une fois qu'un modo aurait choisi son skin, et si player_textures gagne sur u_skins pour le lui mettre, il faudra qu'il embête un joueur avec un accès SSH au serveur pour le changer.

Une solution plus pratique serait de modifier u_skins pour que la liste soit complétée en fonction des privilèges.

Et une solution pratique & simple serait d'ajouter une commande pour que les joueurs puissent changer la couleur de leur nametag, par exemple `/set_nametag <normal|moderator|administrator>` (la commande vérifie bien sûr les privs, server permettrait d'utiliser le nametag "administrator" et kick permettrait d'utiliser le nametag "moderator"). À voir.

Dans tous les cas, il est fondamental que quelque soient les privilèges du joueur, celui-ci puisse choisir d'avoir une apparence normale ou qui montre ses privilèges. L'étiquetage ne doit pas être obligatoire.

**Comment by mgl512** [comment]
Je suis opposé à l'idée d'utiliser des privilèges de jeu pour constituer une caste. Je ne connais aucun joueur qui a demandé à ce que les modérateurs soient distingués par des couleurs ou des skins à part. Ce n'est pas une idée qui répond à un besoin organisationnel, c'est juste étaler ses privilèges. Les privilèges, on les a pour améliorer le monde, pas pour parader avec.
