### ISSUE TITLE
Hall of Shame : pb de regexp ds la transcription ?

### ISSUE THREAD

**Issue by mgl512** [Mynetest/Mynetest-server#31]
Un truc bizarre avec le Hall of Shame:

Voilà ce que xban dit dans les logs pour 2 joueurs bannis pour la même raison (reprise avec la même faute de frappe)
```
[xban] Le_Docteur bans 0639569 until sam. 29 oct. 2016 18:43:01 CEST for reason: Plaving a locked chest in public field
[xban] Le_Docteur bans Dimino695 until sam. 29 oct. 2016 18:43:56 CEST for reason: Plaving a locked chest in public field
```

Et comment ça se traduit sur la page [Hall of Shame](http://mynetest.langg.net/hos/)
```
: banned for Plaving a locked chest in public field until sam. 29 oct. 2016 18:43:01 CEST.
Dimino695: banned for Plaving a locked chest in public field until sam. 29 oct. 2016 18:43:56 CEST.
```
Le nom du joueur dont le pseudo n'a que des numéros n'apparait pas. J'imagine que c'est un problème de sélection des champs par regexp mais je n'ai pas regardé le code.

**Comment by paly2** [comment]
Ici se trouve la regex: https://github.com/Mynetest/Mynetest-server/blob/master/mods/xban2/html_writer.lua#L27

Je ne connais pas bien les regex. Le problème est sans-doute dû au fait:
- Soit que les caractères numériques [0-9] comprennent le point
- Soit que le point, même échappé avec un \, possède sa signification non-échappée (n'importe quel caractère).

**Comment by mgl512** [comment]
Le manuel sur les expression régulières LUA, qu'ils appellent "patterns" plutôt que regexp, dit que les caractères spéciaux s'échappent par un **%** devant eux. "Le caractère **.**" = "**%.**". "Un chiffre"  = "%d".

**Comment by paly2** [comment]
J'ai fix la regex, le hall of shame sera mis à jour lors du prochain redémarrage du serveur (s'il est mis à jour avant, la modification ne sera pas prise en compte).
