### ISSUE TITLE
Serveur stoppé

### ISSUE THREAD

**Issue by mgl512** [Mynetest/Mynetest-server#32]
Bloqué après un rollback_check avec les paramètres dans le désordre !
Mynetest a quitté mais pas le serveur. Impossible de terminer le processus:
```
Le_Docteur@langg:~$ pkill minetestserver
pkill: killing pid 16449 failed: Operation not permitted

Le_Docteur@langg:~$ groups
Le_Docteur ssh minetest-admins
```
Le pire c'est que j'ai fait attention à bien passer 0 en premier paramètre. Ensuite 100.000 et pas 1 million. Et j'ai vu que la commande cherchait dans les 100.000 blocs autour :/ 

Le serveur est resté planté 20 minutes avant de recevoir un SIGTERM, par AcidDragon j'imagine.

**Comment by paly2** [comment]
Nous avons réorganisé le lancement du processus minetest et les emplacements des fichiers. Tous les admins doivent maintenant se connecter sous l'utilisateur minetest (utilisateur sous le nom duquel est lancé le processus, ce qui évite les erreurs `Operation not permitted`) en SSH. Leur authentification se fait au moyen de leur clé publique (pas par mot de passe): tu dois donc t'en générer une et nous la transmettre par l'IRC.

**Comment by mgl512** [comment]
Comme si je savais faire ça...

**Comment by paly2** [comment]
> Comme si je savais faire ça...

On verra ça sur l'IRC ;-)
