### ISSUE TITLE
Les areas de joueurs peuvent se chevaucher ?

### ISSUE THREAD

**Issue by mgl512** [Mynetest/Mynetest-server#34]
Le bloc (-88,3,-246) par exemple est contenu dans une area de Tanguy, une area de LolaFr et une de Wizard.

Edit: Encore mieux: Christian174 a mis son area SUR la mienne !  Je l'ai redimensionnée celle-là, il a construit juste a la limite

**Comment by paly2** [comment]
Elles ne le peuvent que si un modérateur les a déplacées (/move_area) ou créées (/set_owner).

**Comment by mgl512** [comment]
C'est pour ça que je demande aux joueurs de faire leurs areas eux-mêmes. Les gens qui ont le priv areas n'ont aucune contraite et peuvent donner accès à un joueur a l'area d'un autre. Par exemple une area souterraine invisible dans le HUD. 

C'est très pénible de répéter les memes instructions des dizaines de fois.

**Comment by AcidNinjaFWHR** [comment]
Hep, c'est moi qui ait créé l'area de Christan174, je n'ai pas dû faire attention au chevauchement. Les joueurs ne peuvent pas chevaucher d'area en effet.

**Comment by paly2** [comment]
Que proposeriez-vous pour aider les joueurs a comprendre par eux-mêmes les instructions ? Il existe des mods "area-tutorial" ?

**Comment by AcidNinjaFWHR** [comment]
Je proposerai bien un autre mod, une sorte de mod protector avec les blocs mais proposer 3 blocs différents

La recette serait
-            - mithril -           -
- mithril -  stone  - mithril -
-            - mithril -           -

ce bloc protegerait 15 ou 20 blocs autour,
le même en diamant protégerait 10 ou 15,
etc. tu vois le principe ?
les gens n'arrivent pas avec les areas et nous demandent toujours de l'aide.

**Comment by mgl512** [comment]
On a une vague très durable de joueurs handicapés des areas. Ils arrivent même pas à voir la liste de leurs areas avec leur tél, ils en voient que 2. Même ça il faut le faire pour eux. Il y en a pas mal aussi qui plantent plein de piquets autour de leur maison sans rien faire d'autre. Ils ont juste des piquets que les autres joueurs ne peuvent pas casser pendant un moment mais pas d'area. Et comme ils ne comprennent pas l'anglais... Pour ajouter quelqu'un à une area, quand ils ne nous demandent pas de le faire aussi, ils préfèrent utiliser la pierre du mod markers que les commandes.

**Comment by AcidNinjaFWHR** [comment]
Le ticket étant lié aux chevauchements, nous avons vus que seuls les modérateurs peuvent chevaucher les areas. Concernant la difficulté a créer des areas des débutants, il faudra peut-être envisager un autre ticket ;)
