### ISSUE TITLE
Ile volante au spawn

### ISSUE THREAD

**Issue by mgl512** [Mynetest/Mynetest-server#36]
Il y a du grief d'eau majeur qui vient des différents étages de cette ile tous les jours. Les habitants disent que ce sont des joueurs de passage qui cassent des blocs mais ils griefent aussi avec leur irrigation sans rien en dessous pour retenir l'eau. Il y a des sources multiples qui descendent jusqu'au spawn et l'inondent tous les jours. J'ai mis de la terre incassable sous certains champs mais les griefeurs peuvent toujours casser les cultures à côté des sources ou poser leur propre eau sur les bords (ce que je n'ai jamais vu encore). Le //drain fonctionne très mal sur ces griefs d'eau. 

Il y a aussi le problème que cette ile s'étend chaque jour et qu'elle se voit sur la carte du monde, comme l'autre en construction au sud-ouest. Je ne crois pas que ce soit une bonne idée d'avoir des iles volantes dans le zone du spawn. Et pour l'étendre, ils font bien sûr du grief massif de dirt (réparé à l'est du parc et près de la villa d'Uraza) plutôt que de crafter de la terre.  

Plein d'habitants veulent fly aussi, évidemment. Ils se trompent de subgame je pense.

**Comment by paly2** [comment]
En effet cette île volante nous cause un certain nombre d'ennuis. Je confirme que les demandes de fly pleuvent.

Il faut proposer à ceux qui la construisent de la déplacer plus loin du spawn. Et aussi plus proche du sol le temps de la construire.
