### ISSUE TITLE
Filtrer les nouveaux joueurs

### ISSUE THREAD

**Issue by paly2** [Mynetest/Mynetest-server#37]
Il devient important de mieux filtrer les nouveaux joueurs, afin de ne conserver que les joueurs motivés qui ne grieferont pas, et pourront calmement parler dans un chat non floodé en étant ainsi mieux entendu des modérateurs (qui perdront moins de temps avec les kikoos).

Nous avons deux solutions:
1. Filtrer les joueurs quand ils se connectent pour la première fois
2. Et/ou mettre en place une politique de ban automatique

La première peut être réalisée de plusieurs manières différentes, je suis à l'écoute de toutes les idées - certaines ont déjà été explorées sur l'IRC, n'hésitez pas à les réécrire sur cette issue de manière plus précise.
Une idée consiste à _maîtriser la place du serveur dans la liste de serveurs publics_, afin de lui donner une bonne place sans que tous les kikoos viennent d'emblée dessus (par exemple, la 15-20ème place, au moment où j'écris nous sommes 4ème). Cela pourrait peut-être se faire en calculant le temps que les joueurs doivent attendre pour être téléportés après leur première connexion (actuellement de 5 minutes) à partir de la position du serveur dans la liste de serveurs publics (pour la position est haute, plus le temps d'attente est élevé). Cela permet de rendre le filtre plus rigide lorsque le serveur est en haut et qu'il a besoin de descendre, et plus souple lorsqu'il a besoin de remonter.

Je répète que toutes les idées sont bienvenues, même si elles n'entrent dans aucune des deux solutions indiquées.

**Comment by AcidNinjaFWHR** [comment]
De plus, il est vrai que les nouveaux joueurs ne lisent pas bien les règles et Grieffent énormément. Il y a un vrai travail de fond a faire sur ça,
sur le serveur Framinetest (serveur minetest de Framasoft), ils ont mis un quizz a la connexion, le concept pourrait etre repris.

**Comment by mgl512** [comment]
Le village de matthieu, Woodbury, est à regarder sur ce sujet. Il a inventé un village avec des parcelles à bâtir où il applique des règles raisonnables comme construire des maisons en bois, pas de mine, des choses pour faire ses preuves. Woodbury serait sous cloche et il faurait construire une petite maison apprécié et résoudre une énigme pour en sortir. 

J'aime bien l'idée de Woodbury si c'est un choix volontaire. je n'aimerais pas que ça soit imposé à tous les joueurs. Y mettre tous les joueurs y mettrait tous les griefers de toute manière. 

En tout cas Woodbury est quelque chose à part sur le serveur et je pense qu'il faudra donner des pouvoirs à matthieu pour l'administrer sans en fair un modérateur officiel pour le laisser libre.

**Comment by paly2** [comment]
Les deux idées sont très bonnes.

Pour le QCM, il faudra bien réfléchir aux questions sur l'IRC, qui ne doivent ni être des questions piège, ni avoir des réponses évidentes.

L'idée de Woodbury semble plus difficile à mettre en place, mais elle est inédite - rien de tel n'a jamais été réalisé sur un serveur Minetest, à ma connaissance. Ce que je ne comprends pas, c'est l'intérêt qu'un joueur aurait à accepter de construire une maison à Woodbury et de ne pas pouvoir en sortir tant qu'il ne l'a pas fait, si c'est un choix ?

**Comment by mgl512** [comment]
> Ce que je ne comprends pas, c'est l'intérêt qu'un joueur aurait à accepter de construire une maison à Woodbury et de ne pas pouvoir en sortir tant qu'il ne l'a pas fait, si c'est un choix ?

Plein de joueurs actuels sont prêts à se retrouver enfermés à Woodbury, à ne pas faire de mine, à faire une maison en bois et à résoudre une énigme pour en sortir. C'est comme un event. matthieu n'a pas encore créé assez de parcelles à batir pour tous les candidats. Se retrouver à essayerd'en sortir ensemble est surement plus motivant que de s'y retrouver seul à essayer d'en sortir pour avoir le droit de jouer sur le vrai serveur. Woodbury est à part et je ne crois pas que ça devrait être utilisé pour filtrer les joueurs. 

Pour le questionnaire, on a eu des joueurs turcs, des grecs, des polonais, des allemands, des hollandais, des espagnols. Très peu arrivent à se faire comprendre en anglais. On a très peu de joueurs réguliers de langue naturelle anglaise d'ailleurs. Le sens de questions pourrait leur échapper. 

Faudrait aussi aller faire un tour sur Framinetest voir s'ils ont du grief quand même. Ça serait bête de faire des efforts pour rien. foxcraft est modo chez eux, dit-elle.

**Comment by paly2** [comment]
Nouvelle idée, très simple, qu'on peut facilement tester: créer une commande improbable pour obtenir l'interact, et mettre un panneau au fond du couloir de la première visite, dans le spawn, parmi les règles, qui indique la commande. Ainsi, un joueur qui obtient l'interact a lu les règles.

**Comment by AcidNinjaFWHR** [comment]
Résolu par le https://github.com/Mynetest/Mynetest-server/commit/f1d55b866a1013dd02291bdf4392d7fd1b4a6dd0
Testé ce matin c'est OK on peut mettre ça sur le serveur.

**Comment by paly2** [comment]
Appliqué sur le serveur !
