### ISSUE TITLE
Rollback

### ISSUE THREAD

**Issue by mgl512** [Mynetest/Mynetest-server#38]
Beaucoup de choses ont disparu, comme le sapin de Noel géant (seamoon), la nouvelle maison de seamoon, la ville souterraine de matthieu et Getsuga. Et Celestia et du grief sont revenus. 

Vu que la maison de Christianxxx qui chevauchait mon area a disparu aussi, le rollback date d'avant le 1er novembre, date de l'issue sur les areas. 

J'aurai peut-etre une sauvegarde du sapin et autres trucs où je suis passé. 

Edit: des tas de joueurs me demandent de les rembourser à cause de ce rollback. Je redirige tout vers Upsilon parce que je ne sais pas quoi faire.

**Comment by paly2** [comment]
En effet un rollback a eu lieu sur un grand nombre de zones. Nous n'avons aucune explication à ce rollback.
Pas de problème pour le remboursement, c'est normal. On peut même donner le privilège creative aux joueurs concernés si on leur fait confiance (qui leur permet de s'auto-donner des items en cliquant dessus dans l'inventaire, ce qui exclut la possibilité de se donner des blocs unbreakable avec not_in_creative_inventory=true comme tous ceux de maptools). Super si tu as des sauvegardes, je suis preneur ! De mon côté je vais retenir la leçon et mettre en place des backups automatiques...

**Comment by mgl512** [comment]
J'ai chargé le sapin de Noel géant et Sion, la ville souterraine, comme ils étaient quand j'y suis passé pour la dernière fois (8 nov max). 

Le chargement des fichiers ne se passe pas très bien:
- De la pierre reste (cf la salle des coffres d'AcidDragon à Sion)
- Une partie des blocs n'est pas chargée (le dome de sion ignoré à x>=64)

Cerise sur le gateau, j'ai effacé le debug.txt du serveur au lieu du mien dans ces opérations.

**Comment by paly2** [comment]
https://github.com/Mynetest/Mynetest-server/commit/c7ef6069f3831fdb6fc4705cde114b28540f1f4d et https://github.com/Mynetest/Mynetest-server/commit/f39fd8a7072ea4c3fa55c8d2e5c7f6708cf6fada

Un backup a lieu chaque nuit à 04:30 (le serveur s'éteint à 04:25).
Les nuits des premiers du mois: écrase le backup du mois précédent (backup monthly)
Les nuits des lundis: écrase le backup de la semaine précédente (backup weekly)
Les autres nuits: écrase le backup de la nuit précédente (backup nightly).
Ainsi, en cas de problème, nous aurons un backup datant de la dernière nuit, un datant de la dernière semaine, et un datant du dernier mois.

**Comment by mgl512** [comment]
Un système de pro !

Plein de maisons et de constructions ont disparu. Dont celles de joueurs qui se connectent rarement comme Baobab, la tour ronde dans l'eau au coin du pont. Son jardin a été rollback. Daeam construit de belles choses au bout de son chemin de fer dont je n'ai pas de sauvegarde récente. La gare de matthieu est perdue.

**Comment by paly2** [comment]
> Un système de pro !

Il nous vient d'AcidDragon !

Malheureusement, nous n'avons pas plus d'explication à ce rollback que de solution pour l'annuler...

**Comment by mgl512** [comment]
Il y a une plateforme en têtes de Nyan à 64 de haut au dessus du spawn, dans l'area du 1er batiment de Sporax. Rien de récent dans les logs. Ça vient du rollback ?

J'ai restauré toutes les constructions que j'avais je pense. Je n'ai qu'une demi-maison de seamoon mais le reste est plutôt bien, à part la gare perdue de matthieu. Il reste à enlever Celestia, qui est revenue. Plus ses ares et ses panneaux. Daeam fait de belles constructions mais elles sont loin. Il/elle en a peut-être perdu.

**Comment by AcidNinjaFWHR** [comment]
Salut, c'était ma plateforme, je l'avais supprimée déjà avant le rollback, je l'ai resupprimée hier soir.

Sinon les gens ont commencés à bien reconstruire, matthieu8fr est en train de faire une sorte de ville avec une mairie et tout, c'est pas mal.

Concernant le rollback, nous ne pouvons plus rien restaurer à priori. Cloture le ticket quand tu veux mgl512.

**Comment by mgl512** [comment]
En plus du système de sauvegarde de la base, j'aimerais quelque chose comme un logrotate du fichier de logs. On a besoin de conserver un ou deux mois de logs pour traquer occasionnellement un usurpateur de comptes mais on n'a même pas besoin que tous ces mois soient dans le même fichier. Et on a encore moins besoin d'accumuler les logs de tous les mois passés dans le debug.txt dans lequel on fait des recherches courantes qui portent sur le grief ou les vols des derniers jours. Ça serait bien d'en faire une rotation tous les mois en espérant que ça ne coupe pas trop souvent au milieu du weekend.

**Comment by AcidNinjaFWHR** [comment]
bah du coup, le plus simple serait de configurer le debug.txt avec logrotate:

https://doc.ubuntu-fr.org/logrotate

on pourrait mettre comme paramètres:
```
/home/.minetest/debug.txt {
	monthly
	rotate 12
	compress
	delaycompress
	missingok
	notifempty
	create 644 minetest minetest
	size 100MB
}
```

**Comment by paly2** [comment]
Logrotate a été mis en place. Configuration utilisée:
```
/home/minetest/.minetest/debug.txt {
        weekly
        rotate 10
        compress
        delaycompress
        missingok
        notifempty
        create 644 minetest minetest
        size 100MB
}
```
