### ISSUE TITLE
Conflit de recettes fishing:bait_worm / default:dirt_with_dry_grass

### ISSUE THREAD

**Issue by mgl512** [Mynetest/Mynetest-server#39]
landcraft: dirt, dirt --> 2 dirt_with_dry_grass
fishing: dirt, dirt --> 8 fishing:bait_worm

la recette des vers était: dirt, group:stick --> 8 fishing:bait_worm, "de la terre touillée" avant que fishing devienne un module.

**Comment by AcidNinjaFWHR** [comment]
Proposition:
![proposition_1](https://cloud.githubusercontent.com/assets/20411249/20644204/53bb14cc-b42d-11e6-92c1-91ac0e28d1cd.png)

![proposition_2](https://cloud.githubusercontent.com/assets/20411249/20644206/575fae9e-b42d-11e6-85b2-6e5b385710bf.png)

Comme ça on garde dirt + dirt pour les fishing:bait_worm.

et comme ça on garde fishing en sous-module et donc d'origine.

**Comment by Nildeala** [comment]
👍

**Comment by mgl512** [comment]
Sauf que l'herbe se crfate pas, elle se ramasse. Ça rend pénible la création de blocs en quantité suffisante et ça encourage la dévastation du paysage. Tout ça est contraire à l'idée de mon mod landcraft de pouvoir crafter facilement tous les blocs de paysage, dissuader le grief et permettre à tous les joueurs de le réparer quand ils en trouvent.

Je trouverais plus acceptable un seul bloc d'herbe sur 2 couches de terre pour obtenir 6 blocs de terre herbeuse.

**Comment by AcidNinjaFWHR** [comment]
Fait.
