### ISSUE TITLE
Rendre le hopper compatible avec l'autocrafter

### ISSUE THREAD

**Issue by AcidNinjaFWHR** [Mynetest/Mynetest-server#41]
A tester ça devrait etre compatible:

https://github.com/Mynetest/hopper

**Comment by AcidNinjaFWHR** [comment]
Impeccable ça marche:
![capture du 2016-11-26 23-14-51](https://cloud.githubusercontent.com/assets/20411249/20644227/2579a74e-b42e-11e6-9885-f78a4cd83c35.png)

**Comment by AcidNinjaFWHR** [comment]
Fixed in afdbacacfbf1936b728d57a271e637b7724a1a3b

**Comment by paly2** [comment]
Magnifique, merci !

**Comment by AcidNinjaFWHR** [comment]
J'ai également rendu le hopper compatible avec les shared_chests ! :)
