### ISSUE TITLE
Base XBan2 encore effacée !

### ISSUE THREAD

**Issue by mgl512** [Mynetest/Mynetest-server#42]
```
2016-11-27 14:01:18: WARNING[Main]: [xban] Unable to load database: Deserialization failed
2016-11-27 14:05:11: WARNING[Main]: [xban] Unable to load database: Deserialization failed
```
Plus de bannis !

**Comment by paly2** [comment]
Arrangé TTTNBS ! (*Thanks To The New Backup System*)

**Comment by mgl512** [comment]
Encore !
`2016-12-07 19:26:41: WARNING[Main]: [xban] Unable to load database: Deserialization failed`

**Comment by paly2** [comment]
Re-corrigé. Il faudrait comprendre la cause de ces corruptions de base de données.

**Comment by AcidNinjaFWHR** [comment]
Salut,
j'ai parlé avec kaeza sur irc et il a ajouté un truc tout con: le détail de l'erreur du Deserialize:
https://github.com/minetest-mods/xban2/commit/97fb251ad954a5927a4ba59e72cffd277e6d244c
Donc on aura l'erreur quand ça se produira... mais faut continuer à faire backup journalière de ca. Et idéalement garder les X derniers jours au cas où on ne remarque pas...

**Comment by mgl512** [comment]
> j'ai parlé avec kaeza sur irc et il a ajouté un truc tout con: le détail de l'erreur du Deserialize:
> minetest-mods/xban2@97fb251

Appliqué: 92bdcec5c6b16170035accb10d86d42951f7ea9c
