### ISSUE TITLE
Problème avec la commande /hp

### ISSUE THREAD

**Issue by mgl512** [Mynetest/Mynetest-server#43]
Elle ne marche pas sur sangoku-wallas. Elle marche sur les autres sur lesquels je l'ai utilisée (moi inclus). Je me demande si c'es le tiret dans son pseudo qui ferait partie de caractères spéciaux mal interprétés, si c'est le pseudo qui est trop long et tronqué. Il faut reagrder le code. Je ne sais même pas de quel mod elle vient cette commande. Ni même si elle vient d'un mod.

Ce n'est pas son priv "creative", je me le suis donné et j'ai pu me tuer.

**Comment by paly2** [comment]
Après de nombreux tests en jeu, c'est un problème dû au bouton PvP. Le PvP doit être activé pour que la commande fonctionne.

**Comment by mgl512** [comment]
J'ai fait des tests en singleplayer qui me montrent autre chose: le statut PvP n'a aucune importance, l'armure fait tout. La commande /hp fait (parfois mais pas toujours) des dégâts à l'armure si elle ne me tue pas. J'ai testé armure diams enchanté et armure mithril, les deux avec bouclier mithril. 

Les commandes /hp sont déjouées par l'armure avec beaucoup d'inconsistance. Parfois la commande tue, parfois non. Si elle ne tue pas, on ne constate rien dans le hud, seulement des dégâts sur l'armure. J'ai enchainé les commandes /hp toutes les 3 secondes. Parfois il en faut 1 pour mourir en armure, parfois il en faut 5. Sans armure, aucune commande /hp n'a jamais été déjouée dans mes tests, même avec PvP désactivé. Le record de ces tests, c'est 9 commandes consécutives déjouées avec PvP actif. J'imagine que le mod PvP Button a son rôle là-dedans sinon d'autres serveurs auraientremarqué l'inconsistance de cette commande (comme ils ont remarqué le redimensionnement des areas xD ) 

Ces tests ont aussi montré que, quand on meurt, l'armure peut être jetée au sol alors qu'il y avait plein de place dans le cube d'os. Elle peut même carrément disparaitre (peut-être qu'elle serait réapparue si j'avais rechargé le chunk). Ça arrive assez souvent. 

Content de savoir de quel mod elle vient.

**Comment by paly2** [comment]
Problème de l'engine, donc, qui gère mal les callbacks `on_punchplayer`...

**Comment by mgl512** [comment]
Il y a un commentaire intéressant de tenplus1 sur l'autoheal qui empêche la mort dans un [commit du mod 3d_armor](https://github.com/stujones11/minetest-3d_armor/commit/9105e8403eba036b13793da88876a46f116fea42)

**Comment by AcidNinjaFWHR** [comment]
Ouah pas mal alors il faut mettre -1001 pour ne pas affliger de dégats à l'armure mais pour tuer le joueur, pas mal comme valeur, fallait la trouver ! xD

**Comment by paly2** [comment]
Oui, tenplus1 doit connaître l'engine, parce que ça n'est pas documenté à ma connaissance ;-)

**Comment by mgl512** [comment]
Il n'y a rien du tout dans le code c++ sur catte valeur de -1001. La fonction c++ transforme toute valeur en dessous de 0 en 0. Si quelque chose se passe, c'est dans les scripts LUA.
