### ISSUE TITLE
Warning MAJ MT_Game vs unified_inventory

### ISSUE THREAD

**Issue by mgl512** [Mynetest/Mynetest-server#45]
En plus du code des carts à tester, le MT_Game récent était incompatible avec unified_inventory : si le mod sfinv (Simple, fast Inventory) de MT_Game était actif, unified_inventory n'apparaissait pas. 

unified_inventory a un fix (désactiver sfinv) qui était une pull request mergée récemment. Il faudra le mettre à jour en même temps que MT_Game (ou avant).

**Comment by AcidNinjaFWHR** [comment]
Idem du coté de rubenwardy/email mod qui était incompatible, VanessaE m'a dit qu'elle l'a corrigé dans tous les cas il faudra etre prudents et bien tester oui :)

**Comment by mgl512** [comment]
xdecor est incompatible aussi et c'est déjà le cas sur Mynetest : trois portes et la lampe iron_lightbox sont incraftables.

**Comment by AcidNinjaFWHR** [comment]
Salut, la plupart des mods ont été rendus compatible, y compris https://github.com/rubenwardy/email
Je vais tester ce soir en recompilant mon minetest du master,
la pull request https://github.com/minetest/minetest/pull/4811 a été mergée, elle améliorera grandement les choses aussi ( moins de paquets envoyés au client).
Ainsi nous verrons s'il y a des mods qui restent à corriger.

**Comment by AcidNinjaFWHR** [comment]
Tous les sous-modules défaillants sont à jour sur le dépot et compatible avec cette dernière version. Prêt à mettre sur le serveur donc.

**Comment by mgl512** [comment]
Parmi les mises à jours de minetest_game, j'ai remarqué que les torches ne sont plus des "plantlike" pixelisées. Elles ressemblent à celles de Carbone qu'on utilise avec des animations en plus. Celles qui sont installées sur Mynetest ne sont pas tout à fait compatibles avec les nouvelles default. Personnellement je préfère celles de Carbone mais on pourrait désactiver le mod, le supprimer et garder les nouvelles torches défaut. D'après mes tests, on se retrouverait avec certaines torches aux murs dans une position horizontale, comme des flèches plantées dans les murs. Carbone a peut-être une mise à jour de ses torches aussi, plus élégantes, plus discrètes et plus éclairantes.
