### ISSUE TITLE
xdecor:rope in areas are not protected

### ISSUE THREAD

**Issue by AcidNinjaFWHR** [Mynetest/Mynetest-server#46]
matthieu8fr informed us of the bug.
I started a fix but that doesn't work yet.
https://github.com/Mynetest/Mynetest-server/commit/4fad3f71b969567d58de596eca7f456072313b69

**Comment by mgl512** [comment]
Globalement xdecor est inadapté à un serveur, avec log de rien du tout (pas de logs des mouvements dans les tables d'enchant, workbench), pas de containers verrouillés, cordes pas protégées dans les areas et un auteur qui trouve que qu'encourager le grief ajoute du challenge au jeu. En plus d'avoir des bugs plus conventionnels comme les armures enchantées qui n'ont pas de texture. Pour un mod indispensable, ça fait beaucoup de défauts. 

Je pense que les modifs pour Mynetest devraient se faire dans un fork du xdecor d'origine. MFF a le sien depuis un moment.

**Comment by paly2** [comment]
> Je pense que les modifs pour Mynetest devraient se faire dans un fork du xdecor d'origine. MFF a le sien depuis un moment.

Oui, bonne idée

**Comment by AcidNinjaFWHR** [comment]
Super, j'ai vu que tu l'as mis en sous-module et en plus, les ropes sont désormais protégées.

**Comment by paly2** [comment]
https://github.com/Mynetest/xdecor/commit/e70843a9b34b4f2e036b1b96b8fa4275f432755d
https://github.com/Mynetest/xdecor/commit/a5e8d588587019cb5149ac0284e3d02aa4d0eb0c
https://github.com/Mynetest/xdecor/commit/9a1d0379600a63de1d8eae169eafe391ec265622
Mis à jour sur le serveur dans https://github.com/Mynetest/Mynetest-server/commit/fa5f054f8aeedd086e31ed308f4c52f7bfb06ad4 puis dans https://github.com/Mynetest/Mynetest-server/commit/d44b783d74b733dc5815657154e738302f440de3
