### ISSUE TITLE
Anciens joueurs sans mot de passe

### ISSUE THREAD

**Issue by mgl512** [Mynetest/Mynetest-server#48]
Je suis d'avis de verrouiller les mots de passe de joueurs qui n'en ont pas, qui ne jouent plus et se font régulièrement usurper leur compte. 

paul et pablo se font usurper leurs comptes par accident parce que leur pseudo est commun. Le vrai paul ne joue plus depuis fin septembre (et n'a pas joué de l'été avant) et s'est fait usurper des tas de fois depuis. pablo c'est plus ancien encore (il a une tombe au cimetière qui indique au moins le mois de sa dernière connexion). Un usurpateur de pablo a saccagé le rez-de-chaussée de son manoir, devenu une area publique depuis. Et WolfTueur, qui ne joue plus depuis encore plus longtemps que les autres, s'est à nouveau fait usurper en novembre par le même grand usurpateur que la première fois. Ces trois vrais joueurs sont faciles à identifier s'ils reviennent. Je pense verrouiller leurs comptes en fin d'année si personne ne s'y oppose. Plus stayfino par exemple.

Il n'y a pas de moyen de savoir si un joueur a un mot de passe sans essayer d'usurper son compte ?

**Comment by AcidNinjaFWHR** [comment]
normalement si il devrait y avoir un hash spécial étant donné que le mdp est vide mais je ne sais pas comment sont calculés les hashs, probablement avec un grain de sel ou meme carrément le nom d'utilisateur donc a voir...

**Comment by paly2** [comment]
Les hashs sont calculés avec le mot de passe, et uniquement avec le mot de passe. Deux joueurs avec un mot de passe identique auront un hash identique. Je ne sais pas quel est l'algorithme utilisé, vraisemblablement SHA-2.

Lorsqu'un joueur n'a pas de mot de passe, il n'a pas de hash. Ainsi, pour savoir s'il a un mot de passe, il suffit de consulter le fichier `auth.txt` dans le dossier du monde, par exemple avec la commande:
`grep "^playername:" auth.txt | cut -d ':' -f 2` (en remplaçant bien sûr playername par le nom du joueur)
Si elle affiche un hash, le joueur a un mot de passe, si elle n'affiche rien, il n'en a pas.

**Comment by mgl512** [comment]
Je ne vois aucune différence entre ceux qui ont un mot de passe et ceux qui n'en ont pas. Personne n'a de 2ème champ vide.

**Comment by paly2** [comment]
> Je ne vois aucune différence entre ceux qui ont un mot de passe et ceux qui n'en ont pas. Personne n'a de 2ème champ vide.

En effet je n'ai pas retrouvé de cas sans hash, mais je suis quasiment sûr d'en avoir déjà vu avec 0.4.13, en vérifiant que le mot de passe avait été effacé après un `/clearpassword`. Peut-être que depuis le mécanisme a été complexifié.

**Comment by mgl512** [comment]
Alors que je regardais dans les logs qui s'est connecté récemment avec de vieux pseudos, j'ai remarqué que notre ami le Grand Usurpateur a encore essayé de se connecter le 27 décembre sous son nom originel, bryan200, celui qui avait juste un objet mesecons dans son inventaire, qui a une tribune de l'arène à son nom et dont j'ai verrouillé le mote de passe au moment de l'Usurpation; et sous le nom de WolfTueur, sa victime ultime. Il a réussi son usurpation en mai je crois. Il ne lache rien!

J'ai verrouillé:
- pablo/paloma
- paul (RIP :cry: )
- WolfTueur

Je ferme.

**Comment by mgl512** [comment]
alice, bannie pour faux fly, parlait mal anglais et disait être de Corée du Sud.
Maintenant on a la même alice qui parle français. 
C'est possible qu'il y ait des nouveaux joueurs sans mot de passe ? Ou le compte "alice" a été créé à une époque ancienne et plusieurs fois usurpé ?

**Comment by AcidNinjaFWHR** [comment]
possible que quelqu'un l'ait "usurpé" ou repris sans meme faire expres, possible aussi que ce fut une mytho qui ne venait pas de Corée du Sud mais de France.

**Comment by mgl512** [comment]
C'est 2 ip très différentes et la première n'est plus revenue depuis son ban. Si le serveur _ne permet pas_ de créer de compte sans mot de passe, la "première" alice devait déjà être une usurpation accidentelle. La plus récente arrive sur le serveur, meurt en full mithril + épée nyan + pioche nyan dans les maisons sur l'eau au spawn et ne récupère même pas son stuff (confisqué) dans ses vieux os. Je suis tenté de verrouiller le mot de passe. Je lui ai dit d'en mettre un en jeu. 

Il y a surement des centaines de pseudos sans mot de passe et il n'y a pas de moyen de les repérer. Tester en usurpant le joueur comme on l'a fait avec Uraza en mai n'est pas possible non plus à cause de names_per_ip et parce qu'on protègerait ce pseudo de tout ban.
