### ISSUE TITLE
Téléporteurs pour Woodbury

### ISSUE THREAD

**Issue by mgl512** [Mynetest/Mynetest-server#52]
Les bâtisseurs (matthieu, Grossam) demandent des téléporteurs vers Woodbury. Il y a une arche officielle de téléportation prête quelque part mais ils en voudraient peut-être aussi plus près de chez eux. Je ne connais pas grand chose aux command blocks et je préfère que seul l'admin en pose. Mais je devrais pouvoir mimer celui du spawn si besoin, un teleport @nearest (et repérer le nom du bloc), je ne connais rien d'autre. C'est ok pour qu'Acid ou moi en posions ?

**Comment by paly2** [comment]
Pas de problème pour que vous en posiez.

Un command block ça n'est pas compliqué, il exécute simplement les chatcommands qu'on lui entre, avec une syntaxe supplémentaire remplacée par le nom du joueur le plus proche, du plus eloigné ou bien un joueur aléatoire au moment de son exécution (@nearest, @farthest et @random).

**Comment by mgl512** [comment]
OK. j'en ai installé quelques uns. Je ferme, Acid a surement vu la consigne.

C'est embêtant de pas pouvoir taper de 7 dans les command blocks.
