### ISSUE TITLE
Stats Mynetest

### ISSUE THREAD

**Issue by AcidNinjaFWHR** [Mynetest/Mynetest-server#55]
Salut, j'ai fait un petit truc sympa ce matin: des stats sur les users (à partir du auth.txt)
Ca permet de pister des trucs j'imagine. Est-ce que ca vous interesse d'avoir le fichier?

Stats intéressantes:
31246 joueurs
4295 joueurs connectés depuis le 1er décembre
11903 n'ont pas interact… (ça pollue le auth.txt pour rien dommage)

![capture](https://cloud.githubusercontent.com/assets/20411249/21260046/83c45b54-c384-11e6-927b-5ebc0f9537f9.JPG)

**Comment by mgl512** [comment]
Super compilation de stats !

Il y avait 30.500 joueurs il y a quelques jours. Je trouve qu'il y en a beaucoup qui ont ban. Il m'en manque un dans mon compte alors que je compte jg sans être sûr et 2 fois Upsilon. Upsilon, palige, Uraza, Le_Docteur, AcidDragon, Emure, Fox1000, matthieur8fr, jg. Seamoon ne l'a plus. Qui sont les 2 qui ont kick sant ban, Lord_discodlm57 et BigBoss57 ? 

Il y a des joueurs qui n'ont pas interact à dessein: admin, Admin, Sporax-admin et peut-être public. pareil pour shout. J'ai remarqué que le ban anticipé des "Admin" marche bien dans les logs :)

Ça me rappelle que Getsuga doit avoir fly mais pas fast et qu'il faudrait lui donner. Les builders les plus talentueux (matthieu, Grossam) ont fly et fast sauf PilouP'tichou qui ne vient plus et dont je n'ai jamais compris le problème. Daeam, l'auteur du chemin de fer épique, devrait l'avoir aussi mais il/elle ne vient plus non plus je pense. Il y a surement des fly à retirer à des joueurs comme SkyHal, SkyOrders, qui ne viennent plus sur le serveur depuis longtemps.

**Comment by AcidNinjaFWHR** [comment]
jg et giori ont kick sans ban (je ne connais ni l'un ni l'autre)
Lord_discodlm57 et BigBoss57 ont les 2.
Sporax-admin a interact, public et Admin ne l'ont pas.
Getsuga a bien fly et fast.
Daeam dernière connexion le 28 novembre

Bon en gros, les gens qui ont fly :
![image](https://cloud.githubusercontent.com/assets/20411249/21261218/53d9c086-c38a-11e6-9f72-51e63d0c023a.png)

**Comment by mgl512** [comment]
jg est le frère d'Upsilon. Il ne vient jamais. Je ne sais pas qui est giori. J'espère que c'est un compte qu'Upsilon utilise pour faire des trucs louches sur son serveur. 

Lord_discodlm57 a changé de compte pour BigBoss57. Il y a longtemps, il m'a dit qu'il a donné son mot de passe Lord à un pote et que c'est lui qui a fait du grief. Il faut supprimer les privs de ce compte. disco fait partie des troupes françaises qui attaquent actuellement Daesh à Mossoul avec l'armée irakienne. Ou pas. Il ne reviendra peut-être jamais. 

Wallace2336 est sangokujunior et sangoku-wallas. Il dit que son compte Wallace2336 a été cracké mais il a juste dû oublier son mot de passe. Il faut supprimer son priv fly. Winner a eu fly pour son ile flottante ou ses events je suppose. Mais il a quitté le serveur probablement à jamais il y a quelques jours.

**Comment by paly2** [comment]
Intéressantes en effet ces statistiques ! Je les consulte aussi régulièrement avec des `grep` combinés à des `wc`, notamment.

> Je ne sais pas qui est giori. J'espère que c'est un compte qu'Upsilon utilise pour faire des trucs louches sur son serveur.

Non pas du tout. Je ne sais pas non plus de qui il s'agit.

> disco fait partie des troupes françaises qui attaquent actuellement Daesh à Mossoul avec l'armée irakienne. Ou pas.

C'est un troll qu'il m'a aussi déjà fait.

**Comment by AcidNinjaFWHR** [comment]
Ok. Donc c'est intéressant ça permet de remettre un peu les privs d'équerre.
