### ISSUE TITLE
Bouts de map générés dans du vide

### ISSUE THREAD

**Issue by mgl512** [Mynetest/Mynetest-server#57]
Il y en a plein sur la carte du monde. De touts petis chunks avec du vide autour. Jusqu'en (30_000, 30_000) Qui fait ça, des joueurs légitimes ou des cheaters ?

**Comment by matt8fr** [comment]
Il m'est arriver d'en générer en allant voire un joueur en fast, la map ne charge pas aussi vite que le déplacement du joueur mais pour le déplacement aussi loin je comprend pas !

**Comment by paly2** [comment]
Seuls des clients cheatés (ou alors très, très, buggés) peuvent génèrer la map de cette façon - je ne sais pas si tu te souviens, le "client ultra-cheaté" le faisait aussi.

Ce type de cheat est très difficile à détécter, car un joueur qui se déplace vite peut utiliser le sprint, un joueur qui se téléporte le mod h2omes. Un anticheat devrait prendre tous les mods en compte.

**Comment by mgl512** [comment]
Je me souviens du super cheater qui doit être le même les deux fois. La 2ème fois, il a fait atention à ce genre de générationet qui l'a fait repérer en direct et il est allé sous terre directement, en (20000, -200000, 20000). C'est inquiétant de voir autant de chunks générés par téléportation réelle et pas par saccades comme en cheatant fast et fly.
