### ISSUE TITLE
ERROR[Main]: ServerError: Invalid float vector dimension range 'x'

### ISSUE THREAD

**Issue by mgl512** [Mynetest/Mynetest-server#58]
Le serveur a plein d'erreurs comme ça depuis décembre. 4 le 26 et déjà 2 le 27

**Comment by paly2** [comment]
Je ne sais pas d'où ils viennent, mais ils semblent avoir disparu. (Notre debug actuel commence le 30 décembre, pas de tel message depuis lors.)

Je ferme, réouvrir s'ils réaparraissent

**Comment by mgl512** [comment]
`2017-01-29 10:06:19: ERROR[Main]: ServerError: Invalid float vector dimension range 'x' (expected -2.14748e+06 < x < 2.14748e+06 got -2.14748e+06).`

**Comment by paly2** [comment]
J'ai modifié et recompilé le minetestserver pour que celui-ci affiche un traceback avec ce type d'erreur, qui nous sera d'une grande aide. Il faut attendre un reboot pour que le nouvel exécutable soit chargé.

**Comment by paly2** [comment]
Le traceback a été ajouté dans le dépôt officiel
https://github.com/minetest/minetest/commit/f5070b44542edba97a20445c3774c221077cc4a2

**Comment by mgl512** [comment]
C'est beaucoup plus clair maintenant:
```
2017-02-07 19:13:42: ERROR[Main]: ServerError: AsyncErr: environment_Step: Invalid float vector dimension range 'x' (expected -2.14748e+06 < x < 2.14748e+06 got -2.14748e+06).
2017-02-07 19:13:42: ERROR[Main]: stack traceback:
2017-02-07 19:13:42: ERROR[Main]: 	[C]: in function 'get_areas_for_pos'
2017-02-07 19:13:42: ERROR[Main]: 	/home/minetest/.minetest/mods/areas/api.lua:6: in function 'getAreasAtPos'
2017-02-07 19:13:42: ERROR[Main]: 	/home/minetest/.minetest/mods/areas/hud.lua:10: in function '?'
2017-02-07 19:13:42: ERROR[Main]: 	...e/minetest/minetest/bin/../builtin/game/register.lua:412: in function <...e/minetest/minetest/bin/../builtin/game/register.lua:392>
```

**Comment by paly2** [comment]
En effet la position de l'erreur est claire... sa cause l'est beaucoup moins.

La position est donnée par une méthode `getpos()` sur un joueur, arrondie avec `vector.round()`. J'imagine mal dans quelle condition on pourrait obtenir -2.14748e+06...

**Comment by mgl512** [comment]
Ce ne serait pas qu'une position -x d'une area a été définie au delà de la limite de la map tout simplement ?

**Comment by paly2** [comment]
> Ce ne serait pas qu'une position -x d'une area a été définie au delà de la limite de la map tout simplement ?

Visiblement pas, selon le traceback c'est la position passée en paramètre à la fonction getAreasAtPos qui coince lors de l'appel à [`AreaStore:get_areas_for_pos`](https://github.com/minetest/minetest/blob/master/doc/lua_api.txt#L3063). Cette position est récupérée par la fonction du HUD, est correspond à la position du joueur dont on calcule l'affichage du HUD. Mais pas directement: cette position passe d'abord par [`vector.round`](https://github.com/minetest/minetest/blob/master/doc/lua_api.txt#L1876), qui pourrait mal fonctionner (il semble aussi qu'on observe sur les téléporteurs de MoreMesecons un problème avec [`vector.distance`](https://github.com/minetest/minetest/blob/master/doc/lua_api.txt#L1872)).

**Comment by paly2** [comment]
J'ai mis un fix temporaire afin d'éviter les crashes...

**Comment by mgl512** [comment]
Et si c'était un vecteur nul le problème ? Les fonctions vector.* sont peut-être pas faites pour les vecteurs nuls. Par exemple quand un joueur se fait TP en 0,0,0 à la connexion ou en mourant. Ca arrive encore.

**Comment by paly2** [comment]
> Et si c'était un vecteur nul le problème ?

Le message d'erreur indique bien que le vecteur n'est pas nul, il est immense (sans être infini) 😕

**Comment by paly2** [comment]
Bien que le problème ne soit pas éclaircit, je ferme l'issue, le fix temporaire (devenu définitif) évitant ces erreurs, et aucune piste de solution ne se profilant.
