### ISSUE TITLE
Metre à jour "mobs"

### ISSUE THREAD

**Issue by mgl512** [Mynetest/Mynetest-server#59]
"mobs" a changé depuis mars et on utilise toujours cette version sur Mynetest.

Maintenant c'est une API dans "mobs_redo" et des mods, classés par nature de mobs qu'ils contiennent,  qui l'utilisent: mobs_animal, mobs_monsters, mobs_npc et même mobs_nssm. 

Mynetest modifie des taux de spawn de monstres et loot mais pas l'API je crois. Plus un timer pour les NPCs qui n'existait pas en mars. Je pense que l'API pourrait être un module direct et le reste des modules forkés des originaux. 

Je crois que le changement important c'est qu'on ne peut plus tuer les mobs des autres joueurs s'ils sont dans son area, une plaie sur les serveurs. Mais je ne suis pas sûr. 

Edit: 
Mynetest modifie l'API parce que les NPCs n'ont pas de life timer dans le mod original (ils ont une chance de spawner sur de la brique qui a de la grass_3 comme voisin, donc jamais). Mobs a maintenant des chevaux qu'on peut chevaucher (mod mob_horse), des traders qui échangent divers trucs dont de la clay contre des lingots d'or. Des runes qui permettent de protéger un mob domestiqué contre les coups des autres joueurs. J'ai besoin de ce mod dans ma vie !

**Comment by mgl512** [comment]
J'ai créé des modules comme forks de ceux de tenplus1 dans Mynetest:

- mobs_redo
API modifiée pour Mynetest (lifetimer pour tout type de mob)
- mobs_animal
Le sanglier spawne sur des blocs existants sur la map
- mobs_npc
Le trader spawne
- mobs_monster
Taux de drop de lava orb augmenté
DM spawne plus bas
- mob_horse

Je crois ne rien avoir oublié.

Le monde est beaucoup plus vide qu'avant dans mes tests. Il n'y a pratiquemet pas de sandmonsters dans les déserts par exemple. On verra et on adaptera sur le serveur. 

Il reste à remplacer "mobs" par tout ça, il faut le supprimer et ajouter des liens vers tous ces modules avec les même noms. "mobs_redo" prend le nom de "mobs" dans son 'mod.conf'.

**Comment by mgl512** [comment]
- [x] Supprimer mobs
- [x] Ajouter mobs_redo, module fork Mynetest
- [x] Ajouter mobs_animal, module fork Mynetest
- [x] Ajouter mobs_monster, module fork Mynetest
- [x] Ajouter mobs_npc, module fork Mynetest
- [x] Mettre à jour les changements dans world.mt

Fait par le commit f3efc241c44febff2e745ffe2543509b823da365. 

A ce stade, mobs est remplacé par sa nouvelle version. Comme nouveautés, il y a le trader, des runes de protection à crafter avec un bloc d'or pour protéger des mobs domestiqués, des barres de vie qui s'affichent quand les mobs prennent des dégâts. 

Reste à considérer l'ajout de **mob_horse** sur le serveur. On ne peut chevaucher que son cheval domestiqué. Tout le monde va en vouloir un, je crois que ça pourrait causer des problèmes de lag. On peut toujours tuer les mobs protégés par rune avec une pioche d'admin. je ne peux pas décider seul de l'installer. Il est en module sur Mynetest mais je n'ai fait aucune modif dessus.

**Comment by AcidNinjaFWHR** [comment]
Le serveur a dû crasher ce matin, depuis il est inaccessible car une erreur est en boucle:

```
2017-01-05 15:11:07: ERROR[Main]: ModError: Failed to load and run script from /home/minetest/.minetest/mods/mobs_redo/init.lua:
2017-01-05 15:11:07: ERROR[Main]: /home/minetest/.minetest/mods/mobs_redo/api.lua:48: bad argument #2 to 'max' (number expected, got nil)
2017-01-05 15:11:07: ERROR[Main]: stack traceback:
2017-01-05 15:11:07: ERROR[Main]:       [C]: in function 'max'
2017-01-05 15:11:07: ERROR[Main]:       /home/minetest/.minetest/mods/mobs_redo/api.lua:48: in main chunk
2017-01-05 15:11:07: ERROR[Main]:       [C]: in function 'dofile'
2017-01-05 15:11:07: ERROR[Main]:       /home/minetest/.minetest/mods/mobs_redo/init.lua:5: in main chunk
```

Je ne sais pas comment corriger cela

**Comment by AcidNinjaFWHR** [comment]
```
local abr = tonumber(minetest.setting_get("active_block_range"))
local aoc_range = math.max(aosrb, abr) * 16
```
plante sur la deuxième ligne, active_block_range n'est pas défini ?

**Comment by mgl512** [comment]
> plante sur la deuxième ligne, active_block_range n'est pas défini ?

Manquant dans minetest.conf et sans valeur défaut. Je n'ai pas eu cette erreur en singleplayer et je ne définis pas ce genre de paramètre à la main. Ça doit se faire tout seul. J'imagine que le minetest.conf du serveur a été édité et a eu un problème. Upsilon a touché à ce genre de trucs il y a pas mal de temps à cause des lags clients. Je suppose que ça doit être réglé au minimum sur Mynetest
`active_block_range = 1` ?

**Comment by paly2** [comment]
Aucune ligne n'a disparu. Ce n'est pas l'`active_block_range` qui posait problème, c'était l'`active_object_send_range_blocks`, placé juste au-dessus dans le fichier Lua, et qui n'a jamais existé dans le minetest.conf.

J'ai désactivé mobs en urgence. Je vois ça dans une heure.

**Comment by mgl512** [comment]
Je n'ai pas d' `active_object_send_range_blocks` dans mon minetest. conf et ça ne crashe pas. 

L'erreur citée par Acid précise bien que c'est le paramètre 2 de la fonction max() qui est nil. Et c'est `active_block_range`

**Comment by paly2** [comment]
Ah oui en effet dans l'erreur retranscrite par @AcidNinjaFWHR c'est le deuxième paramètre. Il y a dans le minetest.conf des erreurs qui concernent le premier.

**Comment by paly2** [comment]
https://github.com/Mynetest/Mynetest-server/commit/ea060f3cf6532e1774532b98399e5ad0fe8e476f et https://github.com/Mynetest/mobs_redo/commit/331c458f7aca814ce857fbe90d747d0654051aab devraient améliorer les choses ;-)

**Comment by mgl512** [comment]
> Reste à considérer l'ajout de mob_horse sur le serveur

??
Le problème des chevaux, c'est qu'on ne peut monter que sur un cheval qu'on a domestiqué. Tout le monde va vouloir au moins un cheval et ça risque de faire beaucoup de mobs permanents au même endroit sur le serveur.

**Comment by paly2** [comment]
Ah ! Oui, ça risque de poser des conflits, du lag... Mais bon, les joueurs en ont vraiment envie. Essayons !
Si nous sommes obligés de le retirer à cause de conflits, les joueurs ne pourront blâmer qu'eux-même. Si nous sommes obligés de le retirer à cause du lag, tous les joueurs devraient être d'accord pour le retirer.

**Comment by mgl512** [comment]
Ajouté 253e5af0d2045cf47d885c79cd13b2b80da33ed1
