### ISSUE TITLE
Enlever "Report"

### ISSUE THREAD

**Issue by mgl512** [Mynetest/Mynetest-server#60]
Ce truc ne sert à rien. Il n'y a pas un report sur 500 qui mérite d'être lu. C'est toujours des pseudos de trolls qui signalent n'importe quoi. Si je recevais un mail par report je viderais ma boite à chaque connexion sans rien lire du tout. C'est l'invention d'un serveur sans joueur ça, non ?

Des joueurs me signalent parfois des trucs que j'ai manqués par mail. Ça doit être pareil pour les autres modos. Les reports ne devraient pas polluer ça. 

*mgl512 tried to add the Piece of s**** *label but it wasn't available.*

**Comment by AcidNinjaFWHR** [comment]
Carrément, mais si le code est de @paly2 il faut peut-être l'externaliser, créer un dépot "report" pour y mettre le code, même si l'on ne l'utilise plus. Qu'en pensez-vous ?

**Comment by mgl512** [comment]
Ce n'est pas d'Upsilon à l'origine. On pourrait aussi le conserver mais uniquement pour les joueurs qui ont le priv "kick" et l'utiliser comme un canal de diffusion entre modérateurs présents en jeu. Mais ça ne servirait pas à grand chose non plus je pense. 

Je suis d'accord pour le mettre dans son propre dépot même si on le garde comme radio modo. Parce que j'ai du mal à faire des merge git de modifs upstream dans des dossiers standards de Mynetest liés à rien du tout. Avec 3d_armor par exemple. Tout ce qui est un mod maintenu par quelqu'un d'autre devrait pouvoir être lié à une url git upstream pour fusionner leur modifs le plus facilement.

**Comment by AcidNinjaFWHR** [comment]
Simple, quand tu clones le dépot local, ajoute un remote:
`git remote add-url upstream https://github.com/machin/truc.git`
par défaut t'as le remote origin qui est la branche master de github,
ton dépot local est une copie du remote origin, quand tu fais `git pull` ou `git fetch` ca prends depuis origin,
mais si tu ajoute le remote que je nomme souvent upstream par facilité, il te suffit alors pour mettre à jour le dépot de faire un `git fetch upstream`.

**Comment by mgl512** [comment]
Je fais exactemet ça et je le nomme upstream moi aussi. Ou je fais un fetch directement sur l'url sans remote et j'utilise FETCH_HEAD. J'ai fait ça récemment avec 3d_armor par exemple. Mais quand j'ai essayé de fusionner ses changements avec le dossier standard de Mynetest 3d_armor, il a tenté de mettre à jour le README.md de Mynetest (../../README.md !?!) au lieu de celui de 3d_armor alors qu'il a mergé correctement les autres fichiers. Je n'ai pas pu contenir la mise à jour au dossier 3d_armor. Si 3d_armor était un module ou subtree, ça n'aurait pas pu faire ça.

**Comment by mgl512** [comment]
OK, Acid l'a enlevé. Je ferme.
