### ISSUE TITLE
3d_armor en sous-module

### ISSUE THREAD

**Issue by fwhcat** [Mynetest/Mynetest-server#61]
Salut,
Est-ce qu'on peut mettre 3d_armor en sous-module,
et surtout est-ce qu'on y a fait des modifs ou bien on peut reprendre l'upstream tel quel ?

**Comment by mgl512** [comment]
Upsilon a fait au moins une modif: les 6 objets dans l'inventaire armure qui causaient énormément de messages d'erreur. Une lligne de code dans 3d_armor/armor.lua je pense. 

Je crois que tout ce qui a été fait d'autre c'est d'y mettre puis d'enlever les textures d'armures enchantées et la modif de la fonction /kill reprise en upstream, à laquelle il a ajouté /killme que j'ai mergé sur le dépot. Mais je suis pas sûr qu'il n'y ait rien de plus.

**Comment by paly2** [comment]
Oui, on ne peut pas le mettre dans un sous-module d'origin du dépôt officiel. Par contre, on peut forker 3D_Armor pour le mettre en sous-module.

**Comment by mgl512** [comment]
La plupart des patches historiques ne sont plus applicables parce que le code de 3d_armor a trop changé. 
- [x] Fix more than 5 items in armor inventory
- [ ] Fixing a bug : armor_inv nil value in 3d_armor
- [ ] Fixing a bug (armors duplicate on dead)
- [ ] Dropping armors if we can't put them is bones
- [ ] Don't drop armor when player died if there is the bones mod
- [x] Removing torches from "hot nodes" in 3d_armor


 Ce qui concerne le drop de l'armure n'est pas applicable. Le mod semble essayer de mettre l'armure dans les os et la droppe sinon. Pour la valeur nil, toute la fonction a changé.

**Comment by mgl512** [comment]
Je suis d'avis de le tester comme ça sur le serveur. De prendre des cobayes pour tester la commande /hp avec ses valeurs de -1001 en même temps.

**Comment by paly2** [comment]
6f730adba2214af0c262b8c1b50fa40b375d2e6e, par @mgl512, permet de fermer cette issue. Continuer dans #43 pour l'étrange valeur -1001
