### ISSUE TITLE
Nouveau throwing: torches pas déduites de la pile

### ISSUE THREAD

**Issue by mgl512** [Mynetest/Mynetest-server#62]
Les flèches torchent fonctionnent: on ne peut pas les tirer dans l'area d'un autre. 

Mais quelle que soit la flèche tirée, la pile de torches n'est pas décrémentée.

**Comment by paly2** [comment]
Le principe est que pour crafter une flèche, une torche soit nécessaire. Ainsi, pour chaque flèche craftée, une torche a été consommée par celui qui l'a craftée. Pas besoin donc de décrémenter dans l'inventaire ;-)

**Comment by mgl512** [comment]
Je voulais dire la pile de _flèches_, pas de torches. J'ai confondu les deux mots. La pile de flèches en acier n'et pas décrémentée non plus, ni les flèches en or ni aucun type de flèche.

**Comment by paly2** [comment]
Corrigé dans https://github.com/Mynetest/throwing/commit/98d5fc9449b4788d210ccc19d74e1eace51ba95e, mis à jour dans 1be4ab22e1374976ddf21d991dbe914c7268a1dc
