### ISSUE TITLE
Ile flottante près du centre commercial

### ISSUE THREAD

**Issue by mgl512** [Mynetest/Mynetest-server#63]
J'ai détruit une ile flottante près du centre commercial. Trop base, trop proche du spawn et au dessus d'autres maisons qui auraient été plongées dans le noir. J'ai sauvegardé un fichier sous le nom "snydergd" qui contient cette ile. C'est le nom du joueur qui l'a contruite.

**Comment by paly2** [comment]
Ok très bien
