### ISSUE TITLE
Suggestion de mod: CompassGPS

### ISSUE THREAD

**Issue by fwhcat** [Mynetest/Mynetest-server#68]
Salut,
que pensez-vous du mod https://github.com/Kilarin/compassgps/ ?
ça a l'air génial pour enregistrer l'empalcement de ses amis etc. woodbury, et autres lieux favoris.

Est-ce que ça pourrait être un + pour les joueurs?

**Comment by paly2** [comment]
Effectivement ça semble être une très bonne idée !
Cependant:
* C'est le serveur qui gère les compas (il recalcule leurs indications toutes les 0.1 secondes). Il faut s'attendre à ce qu'il y ait un impact sur les ressources.
* Le mod a l'air un peu compliqué à utiliser, il y a un risque pour qu'il soit sur le serveur et que personne ne l'utilise parce que personne ne comprend pas à quoi servent et comment utiliser les nouveaux items.
* Je ne crois pas que ça soit très utile: quand les joueurs veulent aller quelque part, ils y plantent un pit/home ou demandent à un joueur de les y téléporter
* Et la map en ligne permet de se guider

Le mieux est encore de demander l'avis des joueurs :-)

**Comment by paly2** [comment]
> Le mieux est encore de demander l'avis des joueurs :-)

... et j'ai eu 3 joueurs qui m'on répondu qu'ils le voulaient (soit à peu près la totalité des joueurs qui ont prêté attention à mes explications sur le mod), donc on le met ! On pourra toujours le retirer s'il pose un quelconque problème

**Comment by paly2** [comment]
881aea12da3409f2603a7ac044268ebac980e267
