### ISSUE TITLE
Protection Violation inefficace quand on creuse sous ses pieds

### ISSUE THREAD

**Issue by mgl512** [Mynetest/Mynetest-server#70]
On est tourné à 180° horizontalement mais on peut continuer à casser le bloc protégé. Surement pour ça que Protector téléporte en l'air, suffisamment haut pour espérer que l'outil ne soit plus à portée du bloc. Il y a une fonction de rotation verticale renommée assez récemment similaire à la rotation horizontale.

**Comment by paly2** [comment]
Rotation verticale ajoutée. Dans tous les cas, l'apparition du formspec au bout de 2 tentatives devrait tout à fait empêcher de continuer à casser.

Bien sûr tout cela n'est efficace que sur des clients non-cheatés
