### ISSUE TITLE
Foret publique maudite

### ISSUE THREAD

**Issue by mgl512** [Mynetest/Mynetest-server#71]
EDIT: manque le début, malédiction comme je disais...
Avec matthieu, on fait une foret publique au nord de la mine et près deu champ public : une grande area "public" et de petites areas "public" "open" du diamètre du tronc pour les arbres coupables. Au mieux les joueurs peuvent couper les arbres mais ils ne peuvent pas replanter de sapling, même si le bloc de terre en dessous est "open". le système d'areas marche comme au champ public. 

Pour la foret, quand on essaie de replanter un sapling, on a le message "protection violation": "Votre angle de vue...". Deux joueurs ont testé et moi aussi en me revoquant le priv "areas". Pour le champ, on peut replanter (le cube de terre en dessous de la position de la graine n'est pas open). 

Je ne comprenais rien mais je me demande si ce n'est pas le code du plantage de sapling qui regarde si le sapling va pouvoir pousser maintenant que je tape le message. L'area arbre open est un tube, insuffisant dans ce cas. Pas le temps de vérifier maintenant.

**Comment by paly2** [comment]
> Je ne comprenais rien mais je me demande si ce n'est pas le code du plantage de sapling qui regarde si le sapling va pouvoir pousser maintenant que je tape le message. L'area arbre open est un tube, insuffisant dans ce cas. Pas le temps de vérifier maintenant.

C'est exact: https://github.com/Mynetest/minetest_game/blob/0ae5dab9b3cc305e851117c06213716236377556/mods/default/trees.lua#L460

**Comment by mgl512** [comment]
Une minute plus rapide que moi !

On n'a pas de message dans le chat "Tree will intersect protection", ça échoue ailleurs que sur le volume de l'arbre. Je voyais mes propres messages en double dans le chat quand j'ai testé en jeu, alors c'est à revérifier.
