### ISSUE TITLE
Générer les couleurs pour MT_Satellite

### ISSUE THREAD

**Issue by mgl512** [Mynetest/Mynetest-server#72]
Les blocs de Farming Redo n'ont pas tous une couleur, de nouveaux blocs incassables non plus, et probablement le corail est les buissons de MT_Game. 

Edit: J'ai oublié si c'est possible pour moi de lancer le script qui le fait.

**Comment by paly2** [comment]
Le chemin du script /home/minetest/.minetest/mods/automappercolors.py , normalement tu peux l'exécuter sans problème :) C'est fait

**Comment by mgl512** [comment]
Ça sera pratique d'avoir la commande exacte pour la prochaine fois.
