### ISSUE TITLE
Usebug: vol dans des coffres verrouillés au moyen de hoppers

### ISSUE THREAD

**Issue by mgl512** [Mynetest/Mynetest-server#74]
Par hopper dans une zone sans area. dans plusieurs coffres verrouillés alignés en ([-375..-369], -69, -332). Le joueur a déplacé le hopper de coofre en coffre le 8 février... Un rollback n'a pas restitué les contenus mais le volé a été remboursé. 

J'ai ban le joueur pour "Vol malicieux dans coffre verrouillé..." pour une durée temporaire le temps d'avoir l'avis d'Upsilon.

**Comment by paly2** [comment]
Un grave usebug à corriger...

Pour la durée, tout dépend du joueur: si c'est un joueur régulier qui ne cause pas trop de troubles habituellement, un ban temporaire, si c'est un nouveau joueur qui commence à usebuguer dès son arrivée sur le serveur et qui ne devrait pas perdre grand-chose d'un ban définitif (car il n'a pas passé beaucoup de temps sur le serveur), un ban définitif.

**Comment by paly2** [comment]
https://github.com/Mynetest/hopper/commit/169cbf7ce26d66b9df7859fbf95a6842124cb8ad
puis
https://github.com/Mynetest/Mynetest-server/commit/54d2242067c10f39ef90eda991f7c70238d53ac8

**Comment by mgl512** [comment]
> Pour la durée, tout dépend du joueur

J'ai raté son installation il y a déjà un moment et je ne remarque pas sa présence, donc ça n'est pas un troubleur d'ordre. La première fois que j'ai entendu parler de lui, c'est quelqu'un qui m'a demandé de lui faire une area en grotte et de la partager avec ce joueur. Le vol est en grotte aussi. Je crois qu'il fait partie de ceux qui font des champs à recolte automatique un peu partout (secouage du champ par sticky pistons, hopper pour ramasser) mais je ne suis pas sûr. 

Je lui ai mis un mois en attendant. Je pense que je ne vais rien y changer et voir si des joueurs demandent de ses nouvelles.

**Comment by mgl512** [comment]
Le joueur a siphoné de nombreux coffres dans au moins 3 endroits différents d'après les logs. Il me reste à vérifier à qui sont les coffres du troisième endroit, vers (37,-7621,1689). Ça m'étonnerait que les autres veuillent le revoir.
