### ISSUE TITLE
Les hoppers ne prennent plus dans les autocrafters

### ISSUE THREAD

**Issue by mgl512** [Mynetest/Mynetest-server#75]
Signalé par Getsuga et confirmé en singleplayer. Avant la mise à jour, un hopper sous l'autocrafter prenait l'objet autocrafté

**Comment by matt8fr** [comment]
c'est fwhcat qui a rendu compatible les hoppers avec les autocraft a la dernière mise a jour.

**Comment by paly2** [comment]
C'est moi qui ai volontairement appliqué cela, c'est le fix de l'usebug #74 (qui permettait aux joueur de voler dans les autocrafters, locked_chests, et les shared_chests, qui ont tous des inventaires protégés utilisables uniquement par leurs propriétaires). Normalement les hoppers peuvent toujours y insérer des items.

**Comment by mgl512** [comment]
Getsuga et Yruma ont des machines qui ne marchent plus maintenant. Ils préfèrent comme c'était avant. L'autocrafteur est comme un coffre normal quand il n'est pas dans une area, protégé sinon. On pourrait siphoner un autocrafteur dans une area par hopper seulement s'il est sur la limite inférieure s'il redevenait comme avant.

**Comment by paly2** [comment]
D'accord :-)
https://github.com/Mynetest/hopper/commit/3ecd0e12bdaf039bf69e2e612a95ef1d0933f484 et https://github.com/Mynetest/Mynetest-server/commit/b498b7f6a197d1c10ad58de522cb69f03eb5176b
