### ISSUE TITLE
Plus de clone/pull anonyme ??

### ISSUE THREAD

**Issue by mgl512** [Mynetest/Mynetest-server#76]
.gitmodules:
> [submodule "mods/travelnet"]
> 	path = mods/travelnet
> 	url = git@github.com:Sokomine/travelnet.git
> [submodule "mods/pvpplus"]
> 	path = mods/pvpplus
> 	url = git@github.com:Mynetest/pvpplus.git

Avec ça plus de clone/pull possible sans enregistrer une clé SSH dans un compte github. Je n'ai pas pu en tout cas. Les fetch échouent tant que je n'associe pas une clé SSH publique à un compte github.

**Comment by paly2** [comment]
Oups !

**Comment by mgl512** [comment]
Encore:
```
[submodule "mods/serveressentials"]
	path = mods/serveressentials
	url = git@github.com:GunshipPenguin/serveressentials.git
```
