### ISSUE TITLE
Boutons Mesecons actionnés par les tirs de flèches ?

### ISSUE THREAD

**Issue by mgl512** [Mynetest/Mynetest-server#80]
Un joueur a demandé ça, à la Minecraft. 

Les plaques de pression s'activent quand on tire dessus avec des flèches parce qu'une flèche qui touche la plaque est un  item droppé je pense, et que ces items activent les plaques. Mais ça ne marche pas pour les boutons.

**Comment by paly2** [comment]
Pourquoi pas :-)

Cela ne serait supposé fonctionné qu'avec un nouveau type de flèche (une "mesecons arrow", par exemple) ou bien avec un type de flèche déjà existant ?

**Comment by mgl512** [comment]
Avec les flèches meurtrières comme dans Minecraft.
