### ISSUE TITLE
Système de la porte en verre du dome trouvé HS

### ISSUE THREAD

**Issue by mgl512** [Mynetest/Mynetest-server#81]
Celle qui mène au jump. Avec WE, j'ai recopié le système mesecons comme je l'ai trouvé. Des recherches dans les logs n'ont rien montré. Yruama a refait le système avec une porte Not plutôt qu'une lampe pour inverser le signal des pistons. Avec GRIFON ils ont fait un système avec une temporary gate sur un jeu de test pour que la porte s'ouvre plus longtemps. Il y en avait une avant dans les souvenirs de GRIFON. Il semble que la lampe originale du système ait été retournée pour devenir plantée dans le piston plutot que dos au piston. Si elle es plantée dos au piston, ça marche. dans le piston le système ne marche pas. Une mise à jour des mods du serveur aurait causé ça ? 

Yruama a aussi remarqué qu'une porte Not qui boucle sur elle-même dans un petit circuit fermé ne saute pas.

**Comment by matt8fr** [comment]
le système précédent bugé régulièrement, celui actuel me parais trop rapide a la fermeture les joueur mobile auront surement du mal a passer a temps.
le système juste derrière ,(celui, du milieux donc) me parait plus adapté car réglable.

**Comment by mgl512** [comment]
A ça rajoutons la disparition du bouton devant l'un des 2 command blocs de TP en surface: celui en (0, 30_000, -4). Le 27 février à 17 heures, quelqu'un essaie de le casser pour la dernière fois. Vers 19 heures je remarque qu'il est absent. Rien dans les logs. 

Celui d'en face, je l'ai déplacé avec un piston. Ça ne laisse pas de trace dans les logs mais la pose du piston laisse une trace sur le bloc d'à côté. Là rien sur les blocs autour. Je ne vois que Worldedit pour  l'avoir supprimé de manière légitime. 

A noter que le piston a créé et déplacé une copie du texte du panneau jaune au dessus du bouton en même temps que le bouton. L'entité a disparu au déchargement du chunk.

**Comment by matt8fr** [comment]
la pioche admin laisse tel des trace dans les logs ? je dit ça car j'ai quelque fois reboucher des trous dans le verre de la zone de spawn( verre de maptools) bizarre tous ça !

**Comment by mgl512** [comment]
Oui, elle laisse des traces. J'ai remarqué un ou deux trous isolés dans le verre de maptools au sol. C'était Fox1000 et sa pioche d'admin.

**Comment by paly2** [comment]
Ce problème de la porte devrait se corriger en rajoutant des temporary gates.
Mais même sans temporary gate, à mon avis, si vous faites plusieurs clics droits successifs sur le bouton, la porte finit par fonctionner (c'est le fameux délais de la MeseTorch)

**Comment by mgl512** [comment]
Le problème de départ de la porte c'est, qu'au repos, l'un des pistons était déployé et pas l'autre. Le système ne marchait plus du tout. Il y en a une copie dans le dome, panneau "Original". Les portes à pistons de la superette de Woodbury étaient déglinguées aussi, avec chaque piston du bas qui semble avoir reculé d'un bloc.

**Comment by paly2** [comment]
Le système refonctionne bien, j'ai laissé la porte No à la place de la torche et ajouté des temporary gate
