### ISSUE TITLE
instalation d'un mod pour le guide

### ISSUE THREAD

**Issue by matt8fr** [Mynetest/Mynetest-server#82]
que pensait vous de [ce mod](https://github.com/taikedz/everamzah-books) pour le guide du spawn ?
il faut pointer dessus ou cliquer pour voire le texte en fromspec (c'est comme ça qu'on dit?) 
donc moins d'entité que les signe actuel.
ps: pensais vous pouvoir ajouter de la couleur au texte ?

**Comment by mgl512** [comment]
Il est en service sur Axinite, qui est l'un des serveurs de l'auteur. Les livres contiennent les règles du serveur là-bas. Ça serait pratique si on ne se faisait pas tuer pendant qu'on est occupé à les lire dans la bibliothèque du PvP de fourbe. Du coup je n'ai pas trop lu ces livres mais ça semble très pratique. Plus pratique que les panneaux. 

D'autres joueurs ont déjà demandé si on pouvait "poser" des livres. Ça ne serait pas utile seulement au spawn. Grossam aurait voulu "poser" une partition devant l'orgue de l'église de Woodbury par exemple. 

Je ne crois pas qu'il y ait des caractères d'échappement de prévus pour changer la couleur d'un texte de formspec mais je ne connais rien aux formspecs. C'est un truc de moteur Lua Minetest: s'il n'y a rien de prévu par le jeu, on ne peut pas le faire.

**Comment by matt8fr** [comment]
j'ai déjà creuser la question il semblerait que se soit possible: [colored chat](https://github.com/minetest/minetest/pull/4077)
heureusement le pvp est désactiver par défaut ici !

**Comment by mgl512** [comment]
Il est dans le dépot mais pas installé sur le serveur. Pareil pour character_creator. J'ai testé le dépot en singleplayer (sans irc_modpack et babelfish) et ça marche. character_creator marche en gardant u_skins.

**Comment by paly2** [comment]
Installé sur le serveur, à présent !

**Comment by matt8fr** [comment]
Il existe une "[extension](https://github.com/taikedz/everamzah-books/tree/magic_pencil)" du mod qui permets d’éditer le livre d'un autre joueur, avec un 'stylo magique' qui demande un privs

**Comment by mgl512** [comment]
> Il existe une "extension" du mod qui permets d’éditer le livre d'un autre joueur

Sa branche "crayon magique" n'est pas encore utilisable:
1. Il a oublié des virgules dans la recette du crayon
2. Le crayon à la recette corrigée crashe le jeu parce qu'il appelle une fonction avec les paramètres dans le désordre et il le sait.
