### ISSUE TITLE
PvPPlus et Throwing en retard

### ISSUE THREAD

**Issue by mgl512** [Mynetest/Mynetest-server#84]
Dans mes mises à jour récentes de submodules, j'ai vu que PvPPlus et surtout throwing ont des liens vers des commits anciens de ces mods. Je ne sais pas si c'est volontaire.

**Comment by paly2** [comment]
Pas vraiment. Je ne les mets pas systèmatiquement à jour sur le serveur quand je leur ajoute des commits.
