### ISSUE TITLE
Vending machines

### ISSUE THREAD

**Issue by mgl512** [Mynetest/Mynetest-server#85]
Plusieurs joueurs ont demandé et demandent un mod de commerce. D'autres s'en passent. 

[Easy vending machines](https://forum.minetest.net/viewtopic.php?f=9&t=15472&p=233410) de Wuzzy permet de configurer une monnaie (lingot d'or par défaut) et de faire des échanges par distributeurs. Acid devait l'avoir sur son serveur et Axinite l'utilise aussi. On ne peut échanger que contre la monnaie définie, comme avec les NPCs traders. C'est aussi le mod d'échange que matthieu voulait pour la partie roleplay de Woodbury, avec les joueurs qui sont exclusivement mineurs ou fermiers ou autre et qui doivent s'échanger des biens.

**Comment by matt8fr** [comment]
Effectivement c'est le mod parfait pour les échange entre joueur, il n'y aura plus de plainte d'arnaque !
