### ISSUE TITLE
Plus d'areas par joueur

### ISSUE THREAD

**Issue by mgl512** [Mynetest/Mynetest-server#87]
Il y a des joueurs qui galèrent avec leurs areas. Le meilleur exemple est haki, qui ne parle pas français. J'ai fait du ménage dans sa trentaine d'areas il y a un moment parce qu'elle ne peut plus s'en créer. Elle est membre de plusieurs groupes qui lui ont donné des areas. Il faut s'adapter à ça, c'est le cas de plein de joueurs. Même en rassemblant ses areas proches les unes des autres, même en en supprimant, elle doit être à près de 15. J'ai dû lui donner le priv areas_high_limit pour ne plus avoir à lui en créer moi-même. Généralement, tous les anciens joueurs ont des problèmes d'area. thomas, le frère de Crystalhola et toutes ses maisons dont l'une a été volée par un autre joueur par manque d'areas est la première victime des areas. Certains joueurs savent qu'on peut se créer un deuxième compte qui créera des areas à transférer au premier et le font. 

Il faudrait doubler le nombre d'areas et doubler celui de areas_high_limit. Il n'y a pas de risque que les joueurs saturent le spawn, il n'y a plus de place.

**Comment by matt8fr** [comment]
Beaucoup crée des areas puis les abandonne aussi, donc d'autre ne peuvent pas récupérer la zone par la suite.
Soucis aussi avec les Arras partager à 15 quand je passe dans une zone pareille et que je joue sur mon téléphone la liste des areas prend la moitié de l'écran.
Je pense qu'augmenter la taille des zones est une bonne idée.
Pas forcément le nombre.
Et le chant des marker devrais doné que 2 poteaux, 4 les joueurs se prenne la tête à les mettre.
Haki avait protégé sa maison en 5 fois le mois dernier je lui avais refait tout en une.

**Comment by mgl512** [comment]
Je préfère que les gens qui abandonnent une maison laissent l'area (ou la transfèrent à "public"). Sinon elle se fait grief et le serveur est encore plus moche. C'est à nous de patrouiller et détecter les areas abandonnées ou erronées. Les zones vides je les supprime. 

Le HUD rempli d'areas, MFF l'a résolu en 2015 avec son fork. Il n'y a plus qu'une ligne mais il faut examiner la zone avec un outil pour voir toutes les areas du coup.

**Comment by matt8fr** [comment]
Pour le HUD il faudrait pouvoirs taper une cmd du style players_area pour avoir la liste.

**Comment by paly2** [comment]
Je pense que les 10 areas autorisées sont suffisantes - peu de joueurs ont 10 builds, et les joueurs en question ont souvent le privilège area_high_limit. En revanche, la taille oblige beaucoup de joueurs à utiliser plusieurs areas par build. Je vais donc augmenter la taille.
