### ISSUE TITLE
Anti-usebug ne marche pas toujours

### ISSUE THREAD

**Issue by mega-gigaMynetest** [Mynetest/Mynetest-server#88]
J'ai remarqué que le nouveau anti-usebug ne marchait pas pour les joueurs téléphone, en effet, même quand on " viole " une protection, la tête ne tourne pas, et les joueurs peuvent passer la porte, à régler !

**Comment by paly2** [comment]
> à régler !

C'est aux développeurs du client dont tu parles qu'il faut adresser cela.

Impossible, en effet, pour le serveur, d'imposer aux clients de respecter le protocole, malheureusement. Actuellement, la modification de l'angle de vue est traitée en envoyant au client un paquet `TOCLIENT_MOVE_PLAYER`, contenant la position et l'angle de vue du joueur. Libre au client d'obéir (et dans le cas de ce client pour téléphone dont tu parles, il n'obéit pas aux changements d'angle de vue, soit délibérément parce que les développeurs ont décidé que c'était inutile, soit parce qu'il n'est pas à jour dans le protocole réseau).
(Il est plus difficile pour le client d'ignorer le paramètre de position, parce que la désynchronisation induise entre les données du client et celles du serveur aurait des conséquences plus difficiles à gérer, mais pour l'angle de vue ça ne pose généralement aucun problème et passe inaperçu, surtout si le client envoie aussitôt un paquet `TOSERVER_PLAYERPOS` au serveur annulant la requête de celui-ci.)

**Comment by mega-gigaMynetest** [comment]
J'ai compris le problème, ce n'est pas un problème d'appareil, de processeur ou de version ou de client, mais un problème dans le jeu qui est aussi je cas sur ordi et tous apparei.
Ton angle de vision est modifie quand tu as "viole" une PROTECTION, cependant les locked door sont avant tout "owned by", avant même d'être protégée, donc on peut la usebug sans déclencher l'anti-usebug de paly2 qui ne marche que sur les Area, l'angle de vision n'est pas modifie et on passe, problématique non ?... ce qui veut dire qu'on peut usebug une porte mais aussi tout blocks "owned by"

**Comment by paly2** [comment]
Bien vu, et embêtant 😕 
Le seul moyen d'y remédier est de modifier le code des doors pour appliquer le même système.

**Comment by paly2** [comment]
Devrait être rapidement corrigé lorsque https://github.com/minetest/minetest_game/pull/1664 sera fusionné

**Comment by paly2** [comment]
https://github.com/Mynetest/Mynetest-server/commit/9e971eb8b526b3e81c76aed0323a0bcb3f6a1a7a
