### ISSUE TITLE
Blocs édités sans trace dans les logs

### ISSUE THREAD

**Issue by mgl512** [Mynetest/Mynetest-server#89]
Après le bouton du command block du spawn qui disparait sans laisser de trace, c'est maintenant les blocs en nyancat d'une maison qui deviennent de la dirt.

Le bloc en (976,7,817) a été posé comme nyancat le 23 février je crois. Une dizaine de jours plus tard, lui et tous ses voisins nyan au sol et aux murs sont devenus de la dirt sans aucune trace dans les logs. Qui fait ça ? C'est une opération WorldEdit.

Ces blocs venaient d'un event labyrinthe à coffres organisé par un joueur en priv creative. Et pourquoi pas des planches plutot que de la dirt surtout ?

**Comment by matt8fr** [comment]
Sur ce coup je plaide coupable ! j'ai compté plus de 60 nyan-cat je trouver çà trop puis ça piqué les yeux! xd
pk en dirt? pour pouvoirs faire marche arrière.

**Comment by mgl512** [comment]
Les maisons construites avec des richesses sont moches mais les maisons en dirt sont aussi moches. Il faut laisser un panneau au joueur quand tu fais ça.
