### ISSUE TITLE
Minetest: Fin du jump doubleheight

### ISSUE THREAD

**Issue by mgl512** [Mynetest/Mynetest-server#93]
Avec le commit [](url)https://github.com/minetest/minetest/commit/14aa990cdd682b00904c4a84968a6c0e3c31716d, l'équipe Minetest a supprimé le saut plus haut avec sneak. Ça va causer pas mal de problèmes sur différents serveurs dont Mynetest avec les jumps qui utilisent ce système. 

Le fameux ascenseur Minetest est supprimé lui aussi. Tous les glitchs de sneak devenus des fonctionnalités sont supprimés.

**Comment by matt8fr** [comment]
Pour les ascenseurs le mod travelnet règle le soucis mais pour le jump c'est une autre histoire.
Vraiment dommage c’était un plus se doubleheight.
Un mod pour les faire revenir et-il envisageable/faisable ?

**Comment by mgl512** [comment]
Heureusement qu'on a treecapitator pour les arbres aussi. Parce que sinon ce serait pose d'échelles contre le tronc ou échafaudage pour couper un grand arbre sans l'ascenseur. Le pire c'est qu'**ils font ça pour imiter Minecraft**. Minecraft est une crêpe plate comparé à la hauteur qu'il y a dans Minetest (62000 blocs). La dimension verticale éait la seule dont il ne fallait surtout pas s'inspirer...

Des gens écrivent déjà des mods pour l'ascenseur, un outil qu'on à crafter et garder dans l'inventaire par exemple. Pour le jump, il y aura surement des mods pour modifier la physique du monde et metre tout saut à 2 blocs de haut. Ne plus pouvoir franchir un obstacle de 2m de haut sans grief est tragique, surtout sur des mapgens à fort relief comme la v7 ou valleys. 

Le jump du spawn devient infaisable, il repose sur plusieurs glitchs de sneak. sauter à 3 blocs de distance n'est plus possible non plus on dirait.

**Comment by paly2** [comment]
En effet, il serait bien d'ajouter un mod pour combler la suppression de cette fonctionnalité, c'est-à-dire une *rétrogradation* (que les devs appellent un "fix")... Certains sont sans aucun doute déjà en cours d'écriture.

**Comment by mgl512** [comment]
Pour le jump de 2 blocs de haut, ça n'a pas l'air trop difficile de modifier le client pour augmenter la vitesse de saut de 50% si la touche sneak est enfoncée. Ça permet de franchir 2 blocs de haut de manière aussi naturelle qu'avant mais ça ne restaure pas l'ascenseur Minetest qui était quand même LE symbole du jeu. 

J'ai plus de mal à imaginer un mod LUA qui fasse la même chose. Je ne sais pas si on peut modifier cette vitesse en LUA ou s'il faut carrément modifer temporairement la physique du monde pendant un jump + sneak. Mettre temporairement la physique du saut à 1.5 fois sa valeur initiale produirait le même résultat.

**Comment by paly2** [comment]
Il est nécessaire de modifier les paramètres physiques du joueur lorsqu'il appuie sur "SNEAK". Mais c'est plutôt propre, je trouve, par rapport à ce qu'on est souvent obligé de faire quand on scripte Minetest ; et d'ailleurs, je n'ai pas de meilleure fonction de l'API à proposer pour ce type de cas

**Comment by paly2** [comment]
https://github.com/Mynetest/Mynetest-server/commit/2bab9893d293dad114392b5e6ad489f5c180fcdf

**Comment by mgl512** [comment]
Et retour du doubleheight jump dans le commit [Sneak glitch: Detect ledge for 2-node climb-up](https://github.com/minetest/minetest/commit/59911761ef529f118e7ba697d4f5983d43dbb383). Ça ne marche pas tout à fait comme avant: on ne saute haut avec sneak que si le client détecte un promontoire à 2 blocs de haut collé à lui. Sur une surface plate, la hauteur du saut en sneak est la même que sans. C'est le même endroit du code où j'ai modifié mon client pour garder le saut plus haut en sneak sauf qu'ils ont rajouté une détection de promontoire pour une raison inconnue. 

Scoop: les devs pensent à ajouter un bloc décoratif rare, une sorte de totem suivi d'une trainée de blocs en gradient de couleurs, le Colorgrad Feline.

**Comment by matt8fr** [comment]
c'est mieux que les feux de l'amour cette histoire

**Comment by mgl512** [comment]
Les devs ont à nouveau supprimé l'échelle sneak et le double height jump par défaut dans un commit du 20 avril 2017: [Sneak glitch: Set default to false](https://github.com/minetest/minetest/commit/58c083f305d77bd3c7d366c1f0e4a54d80a51719).

Il faut les activer par un mod à la prochaine compilation du serveur. J'ai rajouté le code officiel dans le mod sneak_glitch dans le depot:  90737343150c4ea24c530afa240d1a50df36f9c7 mais je n'ai pas mis à jour le world.mt du serveur pour le moment. Je ne sais pas ce que cette option fait avec le code serveur actuel, ni même si elle existe.
