### ISSUE TITLE
Et paf, le chien ! RIP CandyDog

### ISSUE THREAD

**Issue by mgl512** [Mynetest/Mynetest-server#96]
Le CandyDog est supprimé de mt_game. Il faut faire une copie du répertoire avant mise à jour de mt_game. TenPlus1 a réuni pbj_pup et nyancat dans un seul mod qui s'appelle pbj_pup: [https://github.com/tenplus1/pbj_pup](https://github.com/tenplus1/pbj_pup). On peut utiliser son mod au lieu de faire des copies, il ajoutera dedans tout ce que les devs vont inventer et rejeter dans l'avenir.

Edit:
Le Nyancat ne revient pas bien sûr. Chat et chien sont supprimés.

Thread de la suppression du chien CandyDog: [https://forum.minetest.net/viewtopic.php?f=18&t=17261](https://forum.minetest.net/viewtopic.php?f=18&t=17261)

**Comment by matt8fr** [comment]
il remplace le nyan cat a cause des droit d'auteur par le candydog pour au finale le retiré aussi ! pfiou il faut suivre avec les dev minetest! 😃
