### ISSUE TITLE
Signaux mesecons marchent pas portes mais ascenseurs travelnet si

### ISSUE THREAD

**Issue by mgl512** [Mynetest/Mynetest-server#99]
Les ascenseurs travelnet changent l'état de la porte en fer qui les ferme quand on les prend. Ils l'ouvrent si elle est fermée et la ferment si elle est ouverte. C'est pas eux qui empechent les signaux mesecons de fonctionner ?

**Comment by paly2** [comment]
Non, pour le problème des portes de mesecons j'avais fait il y a quelques jours une pull request sur le minetest game il y 5 jours qui a été mergée il y a 2 jours. Le problème ne sera plus présent à la prochaine maj du mt_game.

https://github.com/minetest/minetest_game/pull/1703
